import { test, expect, type Page } from '@playwright/test';
test('data coverage explains real evidence and source review preserves the lead',async({page},testInfo)=>{
  await page.goto('/');await navigate(page,'Data & accuracy');
  await expect(page.getByRole('heading',{name:'Data & accuracy',exact:true})).toBeVisible();
  await expect(page.getByText('Branch counts are not separate buying teams.')).toBeVisible();
  await expect(page.getByText('Templates active',{exact:true})).toBeVisible();
  await page.getByLabel('Research market',{exact:true}).selectOption('Bengaluru');
  await expect(page.locator('.source-directory-list article')).toHaveCount(1);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.screenshot({path:`artifacts/data-accuracy-${testInfo.project.name}.png`,fullPage:true});
  await navigate(page,'Find businesses');
  const name=testInfo.project.name==='desktop'?'Theobroma — Connaught Place':'Blue Tokai — Hauz Khas';
  await page.getByLabel('Search businesses').fill(name);await page.locator('.business-cell').first().click();
  await page.getByRole('button',{name:'Sources',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Compare a current Google listing'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Published details have differences'})).toBeVisible();
  await page.getByRole('button',{name:'Accept published area',exact:true}).click();
  await expect(page.getByRole('button',{name:'Accept published area',exact:true})).toHaveCount(0);
});
async function navigate(page:Page,name:string){await expect(page.locator('aside.sidebar')).toBeAttached();const menu=page.getByRole('button',{name:'Open navigation'});if(await menu.isVisible())await menu.click();await page.locator('aside.sidebar').getByRole('button',{name:new RegExp('^'+name)}).click();}
test('overview, city search, lead profile, notes, stage and saved list work together',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>localStorage.setItem('grow-mode-v2','demo'));
  await page.goto('/');await expect(page.getByRole('heading',{name:'Your next customer starts with a connection.'})).toBeVisible();
  await navigate(page,'Find businesses');await page.getByLabel('Filter by city').selectOption('Mumbai');
  await page.getByLabel('Search businesses').fill('Sunday People');await expect(page.locator('.business-cell').filter({hasText:'Sunday People'})).toBeVisible();
  await page.locator('.business-cell').filter({hasText:'Sunday People'}).click();await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByLabel('Lead sales stage').selectOption('Sample sent');await expect(page.getByLabel('Lead sales stage')).toHaveValue('Sample sent');
  const save=page.getByRole('button',{name:'Save lead',exact:true});if(await save.isVisible())await save.click();
  await page.getByRole('button',{name:/^Notes/}).click();
  await page.getByPlaceholder('What did you discuss? Sample preferences, purchasing needs, next steps…').fill(`Sample request from ${testInfo.project.name}`);
  await page.getByRole('button',{name:'Add note',exact:true}).click();await expect(page.getByText(`Sample request from ${testInfo.project.name}`,{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close dialog'}).click();await page.getByLabel('Search businesses').fill('');
  await navigate(page,'Shortlist');await expect(page.getByText('Sunday People',{exact:true})).toBeVisible();
  expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});
test('discovery adds sample leads and prepares an editable outreach draft',async({page})=>{
  await page.addInitScript(()=>localStorage.setItem('grow-mode-v2','demo'));
  await page.goto('/');await expect(page.getByRole('heading',{name:'Your next customer starts with a connection.'})).toBeVisible();
  await page.locator('.overview-heading').getByRole('button',{name:/Find more businesses/}).click();
  await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Discover sample leads',exact:true}).click();
  await navigate(page,'Automations');await expect(page.locator('.history-table')).toContainText('completed',{timeout:20000});
  await navigate(page,'Find businesses');await page.getByLabel('Search businesses').fill('Willow Coffee');
  await page.locator('.business-cell').first().click();await page.getByRole('button',{name:'Prepare outreach',exact:true}).click();
  await expect(page.getByLabel('Email body')).toBeVisible();await expect(page.getByRole('button',{name:'Send reviewed email'})).toBeDisabled();
  await page.getByLabel('Email subject').fill('A sample partnership discussion');await page.getByRole('button',{name:'Save draft',exact:true}).click();
  await page.reload();await expect(page.getByLabel('Email subject')).toHaveValue('A sample partnership discussion');
});
test('real businesses are the default and city filters expose their sources',async({page})=>{
  await page.goto('/');
  await expect(page.getByLabel('Workspace data mode')).toHaveValue('live');
  await expect(page.getByRole('region',{name:'Your sales workflow'})).toBeVisible();
  await page.getByRole('button',{name:/02 Mumbai \d+ business locations/}).click();
  await expect(page.getByLabel('Filter by city')).toHaveValue('Mumbai');
  await expect(page.locator('.business-cell')).toHaveCount(12);
  await page.getByLabel('Search businesses').fill('Bombay Canteen');
  await page.locator('.business-cell').click();
  await expect(page.getByRole('dialog')).toContainText('Published reservations contact');
  await page.getByRole('button',{name:'Sources',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('reservations@thebombaycanteen.com');
  await expect(page.getByRole('link',{name:'Official source',exact:true}).first()).toHaveAttribute('href','https://thebombaycanteen.com/pages/contact');
  await expect(page.getByRole('dialog')).toContainText('18 Sept 2026');
  await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('button',{name:'Find more businesses',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText('No paid API key is needed.');
  await expect(page.getByRole('button',{name:'Discover leads',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Close dialog'}).click();
  await navigate(page,'Settings');
  await expect(page.getByRole('heading',{name:'Settings & connections'})).toBeVisible();
  await expect(page.getByText('API keys stay on your server. They are never exposed in the browser.')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});
test('catalogue images, automation creation, pipeline and reports render without browser errors',async({page},testInfo)=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('grow-mode-v2','demo'));await page.goto('/');await expect(page.getByRole('heading',{name:'Your next customer starts with a connection.'})).toBeVisible();
  await navigate(page,'Product catalogue');const image=page.locator('.product-image img').first();await expect(image).toBeVisible();await expect.poll(()=>image.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true);
  await page.locator('.product-image').first().click();await expect(page.getByRole('dialog')).toContainText('Not a B2B quote.');await page.getByRole('button',{name:'Close dialog'}).click();
  await navigate(page,'Automations');await page.getByRole('button',{name:'Create automation'}).click();await page.getByLabel('Routine name').fill(`Test routine ${testInfo.project.name}`);await page.getByRole('button',{name:'Create routine'}).click();await expect(page.getByRole('heading',{name:`Test routine ${testInfo.project.name}`})).toBeVisible();
  await navigate(page,'Sales pipeline');await expect(page.locator('.pipeline-column')).toHaveCount(7);
  await navigate(page,'Reports');await expect(page.getByRole('heading',{name:'Market performance'})).toBeVisible();expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});

test('reviewing a real prospect connects shortlist, draft and scheduled follow-up',async({page},testInfo)=>{
  const name=testInfo.project.name==='desktop'?'Toit — Indiranagar':'Blue Tokai — Hauz Khas';
  await page.goto('/');await navigate(page,'Find businesses');
  await page.getByLabel('Search businesses').fill(name);await page.locator('.business-cell').click();
  await page.getByRole('button',{name:'Qualify & shortlist',exact:true}).click();
  await expect(page.getByLabel('Lead sales stage')).toHaveValue('Qualified');
  await page.getByRole('button',{name:'Relationship',exact:true}).click();
  await page.getByLabel('Next follow-up',{exact:true}).fill('2026-10-01');
  await page.getByRole('button',{name:'Save relationship details',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Relationship details updated');
  await page.getByRole('button',{name:'Prepare outreach',exact:true}).click();
  await expect(page.getByLabel('Email body')).toBeVisible();
  await expect(page.getByRole('button',{name:'Send reviewed email'})).toBeDisabled();
  await expect(page.getByText('Confirm the right recipient',{exact:true})).toBeVisible();
  await page.reload();await navigate(page,'Shortlist');
  await expect(page.locator('.business-cell').filter({hasText:name})).toBeVisible();
  await navigate(page,'Overview');
  await expect(page.locator('.follow-up-list')).toContainText(name);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});

test('daily actions record a call, schedule the next date, and retain the conversation history',async({page},testInfo)=>{
  const name=testInfo.project.name==='desktop'?'The Lodhi':'The Oberoi Bengaluru';
  await page.goto('/');await navigate(page,'Today’s actions');
  await expect(page.getByRole('heading',{name:'Today’s actions',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:/Review prospects/}).click();
  while(!(await page.locator('.daily-row').filter({hasText:name}).count()))await page.getByRole('button',{name:/Show more/}).click();
  await page.locator('.daily-row').filter({hasText:name}).getByRole('button',{name:'Review business'}).click();
  await page.getByRole('button',{name:'Log contact',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Log a conversation'})).toBeVisible();
  await page.getByLabel('Outcome',{exact:true}).selectOption('Interested');
  await page.getByLabel('What happened?',{exact:true}).fill(`Requested a sample catalogue — ${testInfo.project.name}`);
  await page.getByLabel('Sales stage after this contact',{exact:true}).selectOption('Contacted');
  await page.getByRole('button',{name:'Next week',exact:true}).click();
  await page.getByRole('button',{name:'Save contact update',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('tab',{name:/Upcoming/}).click();
  await expect(page.locator('.daily-row').filter({hasText:name})).toContainText('Contacted');
  await page.reload();await page.getByRole('tab',{name:/Upcoming/}).click();
  await page.locator('.daily-row').filter({hasText:name}).getByRole('button',{name:'View details'}).click();
  await page.getByRole('button',{name:'History',exact:true}).click();
  await expect(page.getByRole('dialog')).toContainText(`Requested a sample catalogue — ${testInfo.project.name}`);
  await expect(page.getByRole('dialog')).toContainText('Call · Interested');
  await page.getByRole('button',{name:'Close dialog'}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});

test('product opportunities explain fit and save an editable monthly requirement scenario',async({page},testInfo)=>{
  const name=testInfo.project.name==='desktop'?'Blue Tokai — Malviya Nagar':'Blue Tokai — Vasant Vihar';
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await navigate(page,'Find businesses');
  await page.getByLabel('Search businesses').fill(name);await page.locator('.business-cell').click();
  await expect(page.getByRole('region',{name:'Product opportunity summary'})).toContainText('Actual requirement is unconfirmed.');
  await page.getByRole('button',{name:'Open product opportunity'}).click();
  await expect(page.getByRole('heading',{name:'Why & how much?'})).toBeVisible();
  await page.getByLabel('Lower daily quantity',{exact:true}).fill('80');
  await page.getByLabel('Upper daily quantity',{exact:true}).fill('120');
  await page.getByLabel('Service days / month').fill('25');
  await page.getByLabel('Share supplied by us (%)').fill('50');
  await expect(page.locator('.demand-result')).toContainText('1,000–1,500 sachets/month');
  await page.getByLabel('What did you learn from the buyer?').fill('Planning only. Ask purchasing about preferred sachets.');
  await page.getByRole('button',{name:'Save requirement scenario'}).click();
  await expect(page.getByRole('status')).toContainText('Requirement scenario saved');
  await page.reload();await page.getByLabel('Search businesses').fill(name);await page.locator('.business-cell').click();
  await expect(page.getByRole('region',{name:'Product opportunity summary'})).toContainText('1,000–1,500 sachets/month');
  await page.getByRole('button',{name:'Open product opportunity'}).click();
  await expect(page.getByLabel('Lower daily quantity')).toHaveValue('80');
  await expect(page.getByLabel('What did you learn from the buyer?')).toHaveValue('Planning only. Ask purchasing about preferred sachets.');
  await expect(page.getByText(/Blue Tokai may buy centrally/)).toBeVisible();
  expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(false);
  expect(errors).toEqual([]);
});

test('plain-language guide explains each step and contact filters narrow real businesses',async({page})=>{
  await page.goto('/');await navigate(page,'How it works');
  await expect(page.getByRole('heading',{name:'From a business to a buyer.'})).toBeVisible();
  await page.getByRole('tab',{name:'2 Match'}).click();
  await expect(page.getByRole('tabpanel')).toContainText('Actual demand is unknown until the buyer confirms it.');
  await page.getByRole('button',{name:'Next step',exact:true}).click();
  await expect(page.getByRole('tabpanel')).toContainText('Speak to the right person');
  await page.getByRole('tab',{name:'4 Introduce'}).click();
  await expect(page.getByRole('tabpanel')).toContainText('Email sends only after your review');
  await page.getByRole('tab',{name:'5 Follow up'}).click();
  await expect(page.getByRole('button',{name:'Next step',exact:true})).toBeDisabled();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
  await page.getByRole('button',{name:'Start with a business'}).click();
  await page.getByRole('button',{name:'Filters',exact:true}).click();
  await page.getByLabel('Contact available',{exact:true}).selectOption('phone');
  await page.getByLabel('Brand / business group',{exact:true}).selectOption('Blue Tokai');
  await expect(page.locator('.business-cell').first()).toContainText('Blue Tokai');
  await page.getByLabel('Contact available',{exact:true}).selectOption('email');
  await expect(page.getByRole('heading',{name:'No leads found here yet'})).toBeVisible();
  await page.getByRole('button',{name:'Reset filters',exact:true}).first().click();
  await expect(page.locator('.business-cell')).toHaveCount(12);
});
