import { chromium } from '@playwright/test';
import { mkdirSync, existsSync } from 'node:fs';
const browser=await chromium.launch({headless:true,...(existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const issues=[];page.on('pageerror',error=>issues.push(error.message));page.on('response',response=>{if(response.status()>=400)issues.push(`${response.status()} ${response.url()}`);});
mkdirSync('artifacts',{recursive:true});
await page.goto('http://127.0.0.1:5173');
await page.getByRole('heading',{name:'Your next customer starts with a connection.'}).waitFor();
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'artifacts/overview-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Find businesses',exact:true}).first().click();
await page.getByRole('heading',{name:'Find your next customer'}).waitFor();
await page.screenshot({path:'artifacts/leads-desktop.png',fullPage:true,animations:'disabled'});
await page.locator('.business-cell').first().click();
await page.getByRole('button',{name:'Sources',exact:true}).click();
await page.screenshot({path:'artifacts/business-sources-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Overview',exact:true}).last().click();
await page.screenshot({path:'artifacts/opportunity-preview-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Open product opportunity'}).click();
await page.screenshot({path:'artifacts/opportunity-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('region',{name:'Monthly requirement calculator'}).scrollIntoViewIfNeeded();
await page.screenshot({path:'artifacts/calculator-desktop.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Close dialog'}).click();
await page.goto('http://127.0.0.1:5173/#How%20it%20works');
await page.getByRole('heading',{name:'From a business to a buyer.'}).waitFor();
await page.screenshot({path:'artifacts/guide-desktop.png',fullPage:true,animations:'disabled'});

await page.goto('http://127.0.0.1:5173/#Today');
await page.getByRole('heading',{name:'Today’s actions',exact:true}).waitFor();
await page.getByRole('tab',{name:/Review prospects/}).click();
await page.screenshot({path:'artifacts/today-desktop.png',fullPage:true,animations:'disabled'});
await page.goto('http://127.0.0.1:5173/#Settings');
await page.getByRole('heading',{name:'What works right now',exact:true}).waitFor();
await page.getByText('Local development',{exact:true}).waitFor();
await page.screenshot({path:'artifacts/setup-desktop.png',fullPage:true,animations:'disabled'});
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:5173/#Overview');
await page.getByRole('heading',{name:'Your next customer starts with a connection.'}).waitFor();
await page.screenshot({path:'artifacts/overview-mobile.png',fullPage:true,animations:'disabled'});
await page.goto('http://127.0.0.1:5173/#Today');
await page.getByRole('heading',{name:'Today’s actions',exact:true}).waitFor();
await page.getByRole('tab',{name:/Review prospects/}).click();
await page.screenshot({path:'artifacts/today-mobile.png',fullPage:true,animations:'disabled'});
await page.goto('http://127.0.0.1:5173/#How%20it%20works');
await page.getByRole('heading',{name:'From a business to a buyer.'}).waitFor();
await page.screenshot({path:'artifacts/guide-mobile.png',fullPage:true,animations:'disabled'});
await page.getByRole('button',{name:'Start with a business'}).click();
await page.locator('.business-cell').first().click();
await page.getByRole('button',{name:'Open product opportunity'}).click();
await page.getByRole('region',{name:'Monthly requirement calculator'}).scrollIntoViewIfNeeded();
await page.screenshot({path:'artifacts/calculator-mobile.png',fullPage:true,animations:'disabled'});
console.log(JSON.stringify({issues,horizontalOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)},null,2));
await browser.close();
