import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronRight, Download, Mail, MessageCircle, Pause, Play, RefreshCw, Send, ShieldCheck, SlidersHorizontal, Sparkles, Target, Upload, Users, X } from 'lucide-react';
import Papa from 'papaparse';
import { cities, segments, type Lead } from '../shared/types';
import { defaultBody, defaultSubject, destination, personalise, type Audience, type AudienceFilters, type CampaignConfig, type CampaignDetail, type Candidate, type Channel, type Recipient } from '../shared/campaigns';
import { productTitle } from '../shared/catalogue';
import { api, Badge, Button, EmptyState, Modal, useApp } from './lib';

export function Campaigns(){
  const {data,mode,openLead,navigate,notify,run}=useApp();
  const [filters,setFilters]=useState<AudienceFilters>({channel:'email',city:'',segment:'',productId:'',limit:50});
  const [audience,setAudience]=useState<Audience|null>(null);const [config,setConfig]=useState<CampaignConfig|null>(null);const [campaigns,setCampaigns]=useState<CampaignDetail[]>([]);
  const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [view,setView]=useState<'ready'|'research'>('research');const [excluded,setExcluded]=useState<string[]>([]);
  const [name,setName]=useState('Hospitality product introductions');const [subject,setSubject]=useState(defaultSubject);const [body,setBody]=useState(defaultBody);
  const [busy,setBusy]=useState(false);const [previewId,setPreviewId]=useState('');const [detailId,setDetailId]=useState('');const [reviewed,setReviewed]=useState(false);const [setup,setSetup]=useState(false);const [importing,setImporting]=useState(false);
  const requestId=useRef(crypto.randomUUID());const requestVersion=useRef(0);
  const query=useMemo(()=>new URLSearchParams(Object.entries(filters).map(([key,value])=>[key,String(value)])).toString(),[filters]);
  async function reload(){
    const version=++requestVersion.current;
    try{const [next,history]=await Promise.all([api<Audience>(`/campaigns/audience?${query}`),api<{campaigns:CampaignDetail[];config:CampaignConfig}>('/campaigns')]);if(version!==requestVersion.current)return;setAudience(next);setCampaigns(history.campaigns);setConfig(history.config);setError('');}
    catch(e){if(version===requestVersion.current)setError((e as Error).message);}finally{if(version===requestVersion.current)setLoading(false);}
  }
  useEffect(()=>{setLoading(true);setAudience(null);setExcluded([]);void reload();const interval=setInterval(()=>{if(!data.readOnly&&document.visibilityState==='visible')void reload();},5000);return()=>{requestVersion.current++;clearInterval(interval);};},[query,data.readOnly]);
  const selected=audience?.selected.filter(c=>!excluded.includes(c.leadId))??[];
  const candidates=(view==='ready'?audience?.selected:audience?.candidates)??[];
  const preview=audience?.candidates.find(c=>c.leadId===previewId)??selected[0]??audience?.candidates.find(c=>c.address)??audience?.candidates[0];
  const detail=campaigns.find(c=>c.campaign.id===detailId);
  const channelName=filters.channel==='email'?'Email':'WhatsApp';
  const patch=(key:keyof AudienceFilters,value:string|number)=>setFilters(current=>({...current,[key]:value}));
  let previewBody='Choose an audience to preview your message.',previewSubject=subject,templateError='';
  try{if(preview){previewSubject=personalise(subject,preview,data.settings.company,data.settings.senderName);previewBody=filters.channel==='email'?personalise(body,preview,data.settings.company,data.settings.senderName):(config?.whatsapp.template?.body.replace(/{{1}}/g,()=>preview.name).replace(/{{2}}/g,()=>preview.products.join(' and '))??'Connect WhatsApp Business and load your approved message template to preview it here.');}}catch(e){templateError=(e as Error).message;}
  async function create(){setBusy(true);const result=await run(()=>api<CampaignDetail>('/campaigns',{requestId:requestId.current,name,filters,subject,body,leadIds:selected.map(c=>c.leadId)}));setBusy(false);if(result){requestId.current=crypto.randomUUID();setCampaigns(current=>[result,...current.filter(c=>c.campaign.id!==result.campaign.id)]);setDetailId(result.campaign.id);setReviewed(false);}}
  function downloadAudience(){if(!audience)return;const csv=Papa.unparse(audience.candidates.map(c=>({leadId:c.leadId,business:c.name,channel:filters.channel,contact:c.address,priority:c.priority,status:c.blocked||'Ready',optIn:'',permissionSource:''})),{escapeFormulae:true});const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download='campaign-audience-permissions.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function control(action:'start'|'pause'|'cancel'){if(!detail)return;setBusy(true);await run(()=>api(`/campaigns/${detail.campaign.id}/control`,{action,reviewed}),action==='start'?'Batch queued. The worker will send the reviewed recipients.':`Campaign ${action==='pause'?'paused':'cancelled'}.`);setBusy(false);await reload();setReviewed(false);}
  return <div className="campaign-page">
    <section className="campaign-hero"><div><span className="eyebrow"><Sparkles size={14}/> YOUR OUTREACH, ORGANISED</span><h1>One thoughtful message.<br/><span>Your next 100 conversations.</span></h1><p>Choose the right businesses. Personalise your introduction. Start a reviewed batch and let the queue do the sending.</p><div className="campaign-hero-chips"><span><Check size={13}/>Unique contacts</span><span><Check size={13}/>Reasons behind every rank</span><span><Check size={13}/>You control the start</span></div></div><div className="campaign-orbit"><Send size={32}/><strong>{filters.limit}</strong><span>your batch size</span><small>{channelName} campaign</small></div></section>
    <div className="campaign-steps" aria-label="Campaign workflow">{[['1','Choose your audience','City, buyer type and batch size'],['2','Review the message','Check each recipient and product fit'],['3','Start once. Track progress.','Pause, cancel or resume the queue']].map(([n,title,description])=><div key={n}><b>{n}</b><span><strong>{title}</strong><small>{description}</small></span><ChevronRight size={17}/></div>)}</div>
    {mode==='demo'&&<div className="inline-note">Campaigns use your real-business workspace. Fictional sample contacts cannot be sent messages.</div>}
    {error&&<div className="inline-warning" role="alert">{error} <button onClick={()=>void reload()}>Try again</button></div>}
    <div className="campaign-stat-grid">{[[audience?.matching,'matching businesses'],[audience?.contactable,'unique usable contacts'],[audience?.ready,'with recorded opt-in'],[selected.length,'selected for this batch']].map(([value,label])=><div key={label}><span>{label}</span><strong>{loading?'…':value??0}</strong></div>)}</div>
    <div className="campaign-workbench">
      <aside className="campaign-filter-card"><div className="campaign-panel-title"><SlidersHorizontal size={18}/><h2>Build your audience</h2></div><label>Send through<select aria-label="Send through" value={filters.channel} onChange={e=>patch('channel',e.target.value)}><option value="email">Email · Resend</option><option value="whatsapp">WhatsApp Business · Meta</option></select></label><label>City<select aria-label="City" value={filters.city} onChange={e=>patch('city',e.target.value)}><option value="">All cities</option>{cities.map(city=><option key={city}>{city}</option>)}</select></label><label>Buyer category<select aria-label="Buyer category" value={filters.segment} onChange={e=>patch('segment',e.target.value)}><option value="">All buyer categories</option>{segments.map(segment=><option key={segment}>{segment}</option>)}</select></label><label>Product to introduce<select aria-label="Product to introduce" value={filters.productId} onChange={e=>patch('productId',e.target.value)}><option value="">Best catalogue matches</option>{data.products.map(product=><option key={product.id} value={product.id}>{productTitle(product)}</option>)}</select></label><div className="campaign-batch"><span>How many contacts?</span><div>{[50,100,150].map(count=><button key={count} aria-pressed={filters.limit===count} onClick={()=>patch('limit',count)}>{count}</button>)}</div><label>Custom batch size<input type="number" min={1} max={500} value={filters.limit} onChange={e=>patch('limit',Math.max(1,Math.min(500,Number(e.target.value)||1)))}/></label><small>Up to 500 unique contacts per reviewed batch.</small></div><div className="campaign-connection"><span className={`campaign-status-dot ${config?.[filters.channel].ready?'ready':''}`}/><strong>{data.readOnly?'Preview workspace':config?.[filters.channel].ready?'Sender connected':'Sender setup needed'}</strong><p>{config?`${config[filters.channel].used} / ${config[filters.channel].limit} daily attempts used. Large batches continue over multiple days.`:'Loading sender settings…'}</p><button className="text-link" onClick={()=>setSetup(true)}>View connection steps <ArrowRight size={14}/></button></div></aside>
      <section className="campaign-audience"><div className="campaign-panel-title"><div><span className="eyebrow">STEP 01 / THE RIGHT PEOPLE</span><h2>Best-fit businesses first</h2></div><Button variant="secondary" icon={RefreshCw} onClick={()=>void reload()} busy={loading}>Refresh</Button></div><p className="campaign-explanation">Priority reflects product fit, recent buyer interest, sales stage and source evidence. It is a research order, not a conversion probability.</p><div className="campaign-audience-tabs"><button aria-pressed={view==='research'} onClick={()=>setView('research')}>Research shortlist <span>{audience?.matching??0}</span></button><button aria-pressed={view==='ready'} onClick={()=>setView('ready')}>Ready to send <span>{audience?.selected.length??0}</span></button></div>
      {audience&&selected.length<filters.limit&&<div className="campaign-shortfall"><ShieldCheck size={18}/><span><strong>{selected.length} of {filters.limit} requested recipients are selected.</strong> {audience.duplicates>0?`${audience.duplicates} repeated contact records are excluded. `:''}Public contact details do not establish permission to receive marketing. Record existing opt-ins in lead profiles or import your permission records.</span></div>}
      <div className="campaign-audience-list" aria-busy={loading}>{!loading&&!candidates.length?<EmptyState icon={Users} title={view==='ready'?'No send-ready contacts yet':'No businesses match'} text={view==='ready'?'Review the research shortlist, confirm the correct buyer and record their channel-specific opt-in. Your audience will update automatically.':'Try another city, buyer type or product.'}/>:candidates.map((candidate,index)=><article className="campaign-candidate" key={candidate.leadId}><div className="campaign-candidate-top"><span className="campaign-rank">{index+1}</span><button className="campaign-business" onClick={()=>{const lead=data.leads.find(l=>l.id===candidate.leadId);if(lead)openLead(lead);else notify('Switch to Real businesses to open this profile.','error');}}><strong>{candidate.name}</strong><small>{candidate.city} · {candidate.segment}</small></button><span className="campaign-priority" title="Research priority, not purchase probability">{candidate.priority}<small>/100</small></span></div><p className="campaign-contact">{candidate.address||'Contact research needed'}</p><div className="campaign-candidate-bottom"><Badge tone={candidate.ready?'green':'gray'}>{candidate.blocked||'Opt-in recorded'}</Badge><button onClick={()=>setPreviewId(candidate.leadId)}>Preview message <ChevronRight size={13}/></button>{candidate.ready&&audience?.selected.some(c=>c.leadId===candidate.leadId)&&<label className="campaign-select"><input aria-label={`Include ${candidate.name}`} type="checkbox" checked={!excluded.includes(candidate.leadId)} onChange={e=>setExcluded(current=>e.target.checked?current.filter(id=>id!==candidate.leadId):[...current,candidate.leadId])}/>Include</label>}</div><details><summary>Why this lead is prioritised</summary><ul>{candidate.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><p>Suggested products: {candidate.products.join(', ')||'Review product fit'}</p></details></article>)}</div><div className="campaign-audience-footer"><Button variant="secondary" icon={Download} disabled={!audience?.matching} onClick={downloadAudience}>Export audience</Button><Button requiresWrite variant="secondary" icon={Upload} onClick={()=>setImporting(true)}>Import opt-ins</Button></div></section>
    </div>
    <section className="campaign-compose"><div className="campaign-editor"><span className="eyebrow">STEP 02 / MAKE IT RELEVANT</span><h2>A personal introduction, at scale.</h2><p>Personalisation uses recorded business and catalogue facts. It never invents a buyer’s needs or an order quantity.</p><label>Campaign name<input maxLength={100} minLength={3} value={name} onChange={e=>setName(e.target.value)}/></label>{filters.channel==='email'?<><label>Email subject<input maxLength={180} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea rows={10} value={body} maxLength={6000} onChange={e=>setBody(e.target.value)}/></label><small>Available fields: {'{{business}}, {{city}}, {{category}}, {{products}}, {{sender}}, {{company}}'}</small></>:<div className="campaign-shortfall"><MessageCircle size={20}/><span>WhatsApp uses the approved text template loaded from your Meta account. {'{{1}}'} becomes the business name; {'{{2}}'} becomes matching products.<button className="text-link" onClick={()=>setSetup(true)}>Connect and load template <ArrowRight size={13}/></button></span></div>}</div><div className="campaign-message-preview"><div><span className="eyebrow">RECIPIENT PREVIEW</span>{filters.channel==='email'?<Mail size={20}/>:<MessageCircle size={20}/>}</div><h3>{preview?.name??'Your next business partner'}</h3><p className="campaign-contact">{preview?.address||'No contact selected'}</p>{filters.channel==='email'&&<strong>{previewSubject}</strong>}<pre>{templateError||previewBody}</pre>{filters.channel==='email'&&<small>Your company address, opt-in explanation and a unique unsubscribe link are appended automatically.</small>}<div className="campaign-preview-note"><ShieldCheck size={16}/> Preview only. Nothing has been sent.</div></div></section>
    <div className="campaign-launch"><div><strong>{selected.length} unique recipients selected</strong><p>{data.readOnly?'Connect your private backend to save a campaign and start sending.':'Save this audience and its messages, then review the batch before starting.'}</p></div><Button requiresWrite icon={ArrowRight} disabled={loading||!!error||!selected.length||name.trim().length<3||!!templateError||(filters.channel==='whatsapp'&&!config?.whatsapp.template)} busy={busy} onClick={()=>void create()}>Review {selected.length} messages</Button></div>
    <section className="campaign-history"><div className="campaign-panel-title"><div><span className="eyebrow">STEP 03 / STAY IN CONTROL</span><h2>Your campaigns</h2></div><Badge tone="gray">{campaigns.length} batches</Badge></div>{campaigns.length?<div className="campaign-history-list">{campaigns.map(item=><button key={item.campaign.id} onClick={()=>{setDetailId(item.campaign.id);setReviewed(false);}}><span className="campaign-history-icon">{item.campaign.channel==='email'?<Mail size={20}/>:<MessageCircle size={20}/>}</span><span><strong>{item.campaign.name}</strong><small>{item.recipients.filter(r=>r.status==='accepted').length} accepted · {item.recipients.length} recipients · {new Date(item.campaign.createdAt).toLocaleDateString('en-IN')}</small></span><Badge tone={item.campaign.status==='running'?'green':'gray'}>{item.campaign.status}</Badge><ChevronRight size={17}/></button>)}</div>:<EmptyState icon={Send} title="Your first batch starts here" text="Build an audience above. Once approved, your queue and individual send results appear here."/>}</section>
    {setup&&<Modal title="Connect your campaign sender" subtitle="Keep credentials on the private backend, never in the browser or GitHub." onClose={()=>setSetup(false)}><div className="modal-content campaign-setup"><h3>1. Activate the private workspace</h3><p>The public Vercel preview cannot save or send. Use an authenticated backend with a persistent database and one always-on worker.</p><Button variant="secondary" onClick={()=>{setSetup(false);navigate('Settings');}}>Open workspace settings</Button><h3>2. Connect {channelName}</h3><p>{filters.channel==='email'?'Use your Resend API key, verified sender, company postal address and a public HTTPS backend URL for unsubscribe links.':'Use a Meta access token, phone number ID, supported API version, approved template ID, app secret and webhook verification token.'}</p><p>{config?.[filters.channel].missing.length?`Still needed: ${config[filters.channel].missing.join(', ')}`:'Sender configuration is present. Provider acceptance is checked when sending.'}</p>{filters.channel==='whatsapp'&&<><p>Subscribe the Meta messages webhook to <code>/api/webhooks/whatsapp</code> on your private backend. Verified STOP replies block further campaigns. Use a text body with optional static footer, no media/buttons, and include “Reply STOP to opt out”.</p><Button requiresWrite variant="secondary" busy={busy} onClick={async()=>{setBusy(true);await run(()=>api('/campaigns/whatsapp-template',{}),'Approved template loaded.');setBusy(false);await reload();}}>Load approved Meta template</Button></>}<h3>3. Add your opted-in contacts</h3><p>In a lead profile, open Permissions and record where and when the buyer agreed. For an existing opt-in list, export this audience, fill optIn=yes and permissionSource with your evidence, then import it.</p><h3>4. Review, start and monitor</h3><p>The queue respects your server’s daily limits. “Accepted” means the provider accepted a send request; delivery and replies must be checked with the provider. Failures pause the batch for review.</p></div></Modal>}
    {detail&&<Modal title={detail.campaign.name} subtitle={`${detail.campaign.channel==='email'?'Email':'WhatsApp'} · ${detail.recipients.length} saved recipients · ${detail.campaign.status}`} wide onClose={()=>setDetailId('')}><div className="modal-content"><div className="campaign-shortfall"><ShieldCheck size={18}/><span>{detail.campaign.note}{detail.campaign.nextRunAt&&<strong> Next attempt: {new Date(detail.campaign.nextRunAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</strong>}</span></div>{detail.campaign.email&&<div className="campaign-email-identity"><strong>Sender & footer included with every email</strong><p>From: {detail.campaign.email.from||'Not configured — create a new campaign after sender setup'}<br/>Reply to: {detail.campaign.email.replyTo||detail.campaign.email.from||'Not configured'}</p><p>{detail.campaign.email.company}<br/>{detail.campaign.email.postalAddress||'Postal address not configured'}</p><p>You are receiving this because you opted in to product updates from {detail.campaign.email.company}.<br/>Unsubscribe: a unique link on {detail.campaign.email.appUrl||'your public backend'} will be included.</p></div>}<div className="campaign-results">{(['pending','sending','accepted','failed','uncertain','skipped'] as const).map(status=><span key={status}><b>{detail.recipients.filter(r=>r.status===status).length}</b>{status}</span>)}</div><p className="campaign-explanation">Accepted is a provider receipt, not confirmed delivery, a reply or a sale. Uncertain sends are never retried automatically.</p><div className="campaign-saved-recipients">{detail.recipients.map(recipient=><SavedMessage key={recipient.id} recipient={recipient}/>)}</div>{['draft','paused'].includes(detail.campaign.status)&&detail.recipients.some(r=>r.status==='pending')&&<label className="campaign-review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed these recipients, their recorded opt-ins and the personalised messages. Start sending the pending contacts.</label>}{!config?.[detail.campaign.channel].ready&&<p className="inline-note">Sender setup must be completed before this batch can run. Open View connection steps on the campaign page.</p>}</div><div className="modal-footer"><Button requiresWrite variant="secondary" disabled={['cancelled','completed'].includes(detail.campaign.status)} onClick={()=>void control('cancel')} busy={busy} icon={X}>Cancel pending</Button>{['running','queued'].includes(detail.campaign.status)?<Button requiresWrite icon={Pause} busy={busy} onClick={()=>void control('pause')}>Pause batch</Button>:<Button requiresWrite icon={Play} disabled={!reviewed||!config?.[detail.campaign.channel].ready||!['draft','paused'].includes(detail.campaign.status)} busy={busy} onClick={()=>void control('start')}>{detail.campaign.status==='paused'?'Resume pending':'Start batch'}</Button>}</div></Modal>}
    {importing&&<PermissionImport onClose={()=>setImporting(false)} onSaved={()=>{setImporting(false);void reload();}}/>}
  </div>;
}
function SavedMessage({recipient}:{recipient:Recipient}){return <details><summary><strong>{recipient.name}</strong><span>{recipient.address}</span><Badge tone={recipient.status==='accepted'?'green':'gray'}>{recipient.status}</Badge></summary>{recipient.error&&<p className="inline-warning">{recipient.error}</p>}<p><strong>{recipient.subject}</strong></p><pre>{recipient.body}</pre>{recipient.providerId&&<small>Provider receipt: {recipient.providerId}</small>}</details>;}

export function LeadPermissions({lead}:{lead:Lead}){
  const {run}=useApp();const [channel,setChannel]=useState<Channel>('email');const [note,setNote]=useState('');const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);
  const permission=lead.permissions?.[channel];
  async function save(status:'granted'|'revoked'){setBusy(true);const result=await run(()=>api('/campaign-permissions',{rows:[{leadId:lead.id,address:destination(lead,channel),channel,status,note,confirmed:true}]}),'Contact preference recorded.');setBusy(false);if(result){setConfirmed(false);setNote('');}}
  return <section className="campaign-permissions form-stack"><span className="eyebrow">PERMISSION TO REACH OUT</span><h3>Keep the buyer’s preference on record</h3><p>A published email or phone number is contact information. Record permission only when this buyer has agreed to receive your product messages through this channel.</p><label>Channel<select value={channel} onChange={e=>{setChannel(e.target.value as Channel);setConfirmed(false);setNote('');}}><option value="email">Email</option><option value="whatsapp">WhatsApp Business</option></select></label><div className="inline-note"><strong>{permission?`${permission.status} · ${permission.address}`:'No permission recorded'}</strong>{permission&&<p>{permission.note}<br/>Recorded {new Date(permission.recordedAt).toLocaleString('en-IN')}</p>}</div><label>Where and when did the buyer agree or opt out?<textarea value={note} minLength={10} maxLength={1000} rows={4} onChange={e=>setNote(e.target.value)} placeholder="For example: buyer signed our product updates form on 25 September; reference CRM-104. A website listing alone is not opt-in."/></label><label className="campaign-review-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have a record of this buyer’s preference for this exact contact and channel.</label><Button requiresWrite disabled={!confirmed||note.trim().length<10||lead.demo||lead.suppressed} busy={busy} onClick={()=>void save('granted')} icon={Check}>Record opt-in</Button><Button requiresWrite variant="secondary" disabled={!confirmed||note.trim().length<10||lead.demo} busy={busy} onClick={()=>void save('revoked')}>Record opt-out</Button><small>Existing unsubscribe blocks remain in force. If a contact changes, permission must be recorded again for the new address.</small></section>;
}
function PermissionImport({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){
  const {run,notify}=useApp();const [rows,setRows]=useState<{leadId:string;address:string;channel:string;note:string;status:'granted';confirmed:true}[]>([]);const [checked,setChecked]=useState(false);const [busy,setBusy]=useState(false);
  return <Modal title="Import existing opt-in records" subtitle="Use the audience CSV export. This records permissions; it does not send messages." onClose={onClose}><div className="modal-content form-stack"><p>For contacts who already agreed, fill <code>optIn</code> with <code>yes</code> and <code>permissionSource</code> with where and when they agreed. Leave other contacts blank. Up to 500 rows per import.</p><label>Completed permission CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{setRows([]);setChecked(false);const file=e.target.files?.[0];if(!file)return;if(file.size>1000000){notify('Choose a CSV smaller than 1 MB.','error');return;}const parsed=Papa.parse<Record<string,string>>(await file.text(),{header:true,skipEmptyLines:true});if(parsed.errors.length){notify('The CSV could not be parsed. Check the columns and quoting.','error');return;}const selected=parsed.data.filter(row=>row.optIn?.trim().toLowerCase()==='yes').map(row=>({leadId:row.leadId?.trim(),address:row.contact?.trim(),channel:row.channel?.trim(),note:row.permissionSource?.trim(),status:'granted' as const,confirmed:true as const}));if(!selected.length||selected.length>500||selected.some(row=>!row.leadId||!row.address||!['email','whatsapp'].includes(row.channel)||!row.note||row.note.length<10)){notify('Use leadId, channel, optIn=yes and a permissionSource of at least 10 characters for each approved row (maximum 500).','error');return;}setRows(selected);}}/></label><strong>{rows.length} opt-in records selected</strong><label className="campaign-review-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>These contacts explicitly opted in to our product messages. The source column refers to my actual permission records.</label><Button requiresWrite disabled={!checked||!rows.length} busy={busy} onClick={async()=>{setBusy(true);const result=await run(()=>api('/campaign-permissions',{rows}),'Opt-in records imported.');setBusy(false);if(result)onSaved();}}>Import {rows.length} opt-ins</Button></div></Modal>;
}
