import { useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronRight, Coffee, Copy, Croissant, Download, ExternalLink, FlaskConical, Hotel, Layers3, Leaf, Package, Search, ShieldCheck, SlidersHorizontal, Sparkles, UtensilsCrossed, Wine, X } from 'lucide-react';
import type { Product } from '../shared/types';
import { segments } from '../shared/types';
import { catalogueCsv, productBrief, productFitsLead, productPack, productTitle, productVariants } from '../shared/catalogue';
import { Badge, Button, currency, EmptyState, Modal, useApp } from './lib';
import { updateRoute, useRouteParams } from './navigation';

const selectionKey='grow-product-selection-v1';
const categoryIcons:Record<string,typeof Package>={'Sugar sachets':Coffee,'Jaggery & khand':Leaf,'Baking essentials':Croissant,'Syrups & toppings':FlaskConical,'Drink mixes':Wine,'Mouth fresheners':UtensilsCrossed};
const buyerShortcuts=[{name:'Cafés',label:'Coffee service',icon:Coffee},{name:'Bakeries',label:'Bakery kitchen',icon:Croissant},{name:'Bars & lounges',label:'Bar & beverages',icon:Wine},{name:'Hotels & resorts',label:'Hotel hospitality',icon:Hotel}];
const snapshotDate=(product:Product)=>new Date(product.syncedAt).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});

function loadSelection():string[]{
  try{const value=JSON.parse(localStorage.getItem(selectionKey)||'[]');return Array.isArray(value)?[...new Set(value.filter((id:unknown):id is string=>typeof id==='string'))].slice(0,100):[];}catch{return [];}
}

export function ProductCatalogue(){
  const {data,browse,notify,mode}=useApp();
  const params=useRouteParams();
  const category=params.get('range')||'all',buyer=params.get('buyer')||'all',query=params.get('cq')||'',sort=params.get('order')||'featured';
  const [sampleIds,setSampleIds]=useState<string[]>(loadSelection);
  const [storageAvailable,setStorageAvailable]=useState(true);
  const [compareIds,setCompareIds]=useState<string[]>([]);
  const [panel,setPanel]=useState<'samples'|'compare'|null>(null);
  const [mobileFilters,setMobileFilters]=useState(false);
  const selected=data.products.find(product=>product.id===params.get('item'));
  const categories=[...new Set(data.products.map(product=>product.category))];
  const samples=data.products.filter(product=>sampleIds.includes(product.id));
  const comparisons=compareIds.map(id=>data.products.find(product=>product.id===id)).filter((product):product is Product=>!!product);
  const matches=useMemo(()=>Object.fromEntries(data.products.map(product=>[product.id,data.leads.filter(lead=>productFitsLead(product,lead)).length])),[data.products,data.leads]);
  const searchable=data.products.filter(product=>(buyer==='all'||product.segments.some(segment=>segment===buyer))&&`${product.name} ${product.category} ${product.pitch} ${productBrief(product).uses.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
  const products=searchable.filter(product=>category==='all'||product.category===category).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='matches'?matches[b.id]-matches[a.id]:0);
  const heroProducts=['7161040896163','9285977440500','6613007368355'].map(id=>data.products.find(product=>product.id===id)).filter((product):product is Product=>!!product);
  const setFilter=(key:string,value:string)=>updateRoute({[key]:value==='all'||value===''?null:value});
  const reset=()=>updateRoute({range:null,buyer:null,cq:null,order:null});
  const showProduct=(product:Product)=>{setPanel(null);updateRoute({item:product.id},false);};
  const showBuyers=(product:Product)=>{setPanel(null);browse();updateRoute({product:product.id});};
  const toggleSample=(product:Product)=>{
    const next=sampleIds.includes(product.id)?sampleIds.filter(id=>id!==product.id):[...sampleIds,product.id];
    setSampleIds(next);
    try{localStorage.setItem(selectionKey,JSON.stringify(next));setStorageAvailable(true);}catch{setStorageAvailable(false);notify('Browser storage is unavailable. Your selection will last for this session.','error');}
  };
  const toggleCompare=(product:Product)=>{
    if(compareIds.includes(product.id)){setCompareIds(ids=>ids.filter(id=>id!==product.id));return;}
    if(compareIds.length===3){notify('Compare up to three products. Remove one to add another.','error');return;}
    setCompareIds(ids=>[...ids,product.id]);
  };
  const downloadSelection=()=>{
    const url=URL.createObjectURL(new Blob([catalogueCsv(samples)],{type:'text/csv;charset=utf-8;'}));
    const link=document.createElement('a');link.href=url;link.download='dhampur-green-product-selection.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    notify('Product selection downloaded. No order or sample request has been sent.');
  };

  return <div className={`catalogue-studio ${comparisons.length?'has-comparison':''}`}>
    <div className="catalogue-topline"><span className="eyebrow"><span className="catalogue-live-dot"/> DHAMPUR GREEN / PRODUCT STUDIO</span><div><a href="https://www.dhampurgreen.com/collections/horeca-b2b" target="_blank" rel="noreferrer">Visit your store <ArrowUpRight size={14}/></a><button onClick={()=>setPanel('samples')} aria-label={`Open sample list, ${samples.length} products`}><Bookmark size={15}/>Sample list <span>{samples.length}</span></button></div></div>
    <section className="catalogue-hero" aria-label="Product catalogue introduction">
      <div className="catalogue-hero-copy"><span className="catalogue-hero-kicker"><Leaf size={15}/> YOUR HOSPITALITY COLLECTION</span><h1>Good products.<br/><span>Great possibilities.</span></h1><p>From the first coffee of the day to the last sweet touch. Discover your range, build a sample list, and find the businesses it could serve.</p><button className="button catalogue-hero-button" onClick={()=>document.getElementById('catalogue-results')?.scrollIntoView({behavior:'smooth',block:'start'})}>Explore the collection <ArrowDown size={16}/></button><div className="catalogue-hero-proof"><span><strong>{data.products.length}</strong>curated products</span><span><strong>{categories.length}</strong>product ranges</span><span><ShieldCheck size={16}/>Official product sources</span></div></div>
      <div className="catalogue-hero-visual">{heroProducts[0]&&<img className="catalogue-cover" src={heroProducts[0].image} alt="Dhampur Green sugar sachets with a cup of coffee" fetchPriority="high"/>}<div className="catalogue-visual-shade"/><span className="catalogue-photo-credit">DHAMPUR GREEN · HOSPITALITY RANGE</span><div className="catalogue-mini-collection">{heroProducts.slice(1).map(product=><button key={product.id} onClick={()=>showProduct(product)}><img src={product.image} alt={productTitle(product)}/><span>{product.category}<ArrowUpRight size={13}/></span></button>)}</div></div>
    </section>

    <div className="catalogue-usecases"><div><span className="eyebrow">START WITH THE SERVICE</span><h2>Where will it be used?</h2></div><div>{buyerShortcuts.map(({name,label,icon:Icon})=><button key={name} aria-pressed={buyer===name} onClick={()=>{setFilter('buyer',buyer===name?'all':name);setFilter('range','all');}}><Icon size={21}/><span>{label}<small>{data.products.filter(product=>product.segments.some(segment=>segment===name)).length} products to explore</small></span><ChevronRight size={16}/></button>)}</div></div>

    <div id="catalogue-results" className="catalogue-workspace">
      <aside className={`catalogue-filter-panel ${mobileFilters?'expanded':''}`} aria-label="Catalogue filters"><div className="catalogue-filter-heading"><span><SlidersHorizontal size={16}/> Refine the collection</span><button aria-label="Close catalogue filters" onClick={()=>setMobileFilters(false)}><X size={17}/></button></div><div className="catalogue-range-filters"><h3>PRODUCT RANGE</h3><button aria-pressed={category==='all'} onClick={()=>setFilter('range','all')}><Layers3 size={16}/><span>All products</span><small>{searchable.length}</small></button>{categories.map(range=>{const Icon=categoryIcons[range]||Package;return <button key={range} aria-pressed={category===range} onClick={()=>setFilter('range',range)}><Icon size={16}/><span>{range}</span><small>{searchable.filter(product=>product.category===range).length}</small></button>;})}</div><label className="catalogue-buyer-filter">BUYER CATEGORY<select aria-label="Catalogue buyer category" value={buyer} onChange={event=>setFilter('buyer',event.target.value)}><option value="all">All buyer categories</option>{segments.map(segment=><option key={segment}>{segment}</option>)}</select></label><div className="catalogue-filter-tip"><Sparkles size={20}/><h3>A useful starting point.</h3><p>Buyer matches come from business categories. Confirm the menu, recipe and actual requirement with the buyer.</p></div><button className="text-link" onClick={reset}>Reset catalogue filters</button></aside>
      <section className="catalogue-results-panel" aria-label="Product results"><div className="catalogue-results-heading"><div><span className="eyebrow">THE COLLECTION</span><h2>{category==='all'?'Your product catalogue':category}<span>{products.length}</span></h2></div><Button variant="secondary" className="catalogue-mobile-filter" icon={SlidersHorizontal} aria-expanded={mobileFilters} onClick={()=>setMobileFilters(!mobileFilters)}>Filters</Button></div>
        <div className="catalogue-search-row"><div className="input-search"><Search size={18}/><input aria-label="Search products" value={query} placeholder="Search a product, ingredient or use…" onChange={event=>setFilter('cq',event.target.value)}/>{query&&<button aria-label="Clear product search" className="icon-button" onClick={()=>setFilter('cq','')}><X size={15}/></button>}</div><select aria-label="Sort products" value={sort} onChange={event=>setFilter('order',event.target.value)}><option value="featured">Catalogue order</option><option value="name">Name: A–Z</option><option value="matches">Most category-fit prospects</option></select></div>
        {(category!=='all'||buyer!=='all'||query)&&<div className="catalogue-active-filters">{[['range',category==='all'?'':category],['buyer',buyer==='all'?'':buyer],['cq',query]].filter(([,value])=>value).map(([key,value])=><button key={key} aria-label={`Remove catalogue filter ${value}`} onClick={()=>setFilter(key,'all')}>{value}<X size={12}/></button>)}<button className="text-link" onClick={reset}>Clear all</button></div>}
        <div className="catalogue-result-note"><span>{products.length} of {data.products.length} products</span><span><ShieldCheck size={13}/>Retail snapshots, not trade quotes</span></div>
        {products.length?<div className="catalogue-product-grid">{products.map(product=><article className={`catalogue-product-card tone-${categories.indexOf(product.category)%6}`} key={product.id} aria-label={productTitle(product)}>
          <div className="catalogue-card-photo"><button className="product-image" aria-label={`View ${productTitle(product)}`} onClick={()=>showProduct(product)}><img src={product.image} alt={product.name} loading="lazy"/><span className="catalogue-image-link"><ArrowUpRight size={20}/></span></button><span className="catalogue-category-tag">{product.category}</span><button className={`catalogue-sample-button ${sampleIds.includes(product.id)?'selected':''}`} aria-label={`${sampleIds.includes(product.id)?'Remove':'Add'} ${productTitle(product)} ${sampleIds.includes(product.id)?'from':'to'} sample list`} aria-pressed={sampleIds.includes(product.id)} onClick={()=>toggleSample(product)}><Bookmark size={17} fill={sampleIds.includes(product.id)?'currentColor':'none'}/></button></div>
          <div className="catalogue-card-body"><span className="catalogue-card-pack"><Package size={12}/>{productPack(product)}</span><h3><button onClick={()=>showProduct(product)}>{productTitle(product)}</button></h3><p>{product.pitch}</p><div className="catalogue-application-tags">{productBrief(product).uses.slice(0,2).map(use=><span key={use}>{use}</span>)}</div><div className="catalogue-price-line"><strong>{currency(product.price,false)}</strong><span>retail snapshot<small>{snapshotDate(product)}</small></span></div><div className="catalogue-card-actions"><button className="catalogue-buyer-link" aria-label={`Find buyers for ${product.name}`} onClick={()=>showBuyers(product)}><span><strong>{matches[product.id]}</strong> {mode==='demo'?'sample matches':'category-fit prospects'}</span><ArrowUpRight size={15}/></button><label className="catalogue-compare-toggle"><input type="checkbox" checked={compareIds.includes(product.id)} disabled={compareIds.length>=3&&!compareIds.includes(product.id)} onChange={()=>toggleCompare(product)} aria-label={`Compare ${productTitle(product)}`}/>Compare</label></div></div>
        </article>)}</div>:<EmptyState icon={Search} title="No products match these filters" text="Try another product name, buyer type or range." action={<Button variant="secondary" onClick={reset}>Reset catalogue filters</Button>}/>}
        <div className="catalogue-trade-note"><span><Package size={23}/></span><div><h3>Build the conversation. Confirm the commercial details.</h3><p>Prices belong to the recorded packs and sync dates. Confirm bulk pack sizes, minimum order quantities, stock, delivery and trade pricing with your team before quoting.</p><a href="https://www.dhampurgreen.com/collections/horeca-b2b" target="_blank" rel="noreferrer">Open the official hospitality range <ArrowUpRight size={14}/></a></div></div>
      </section>
    </div>

    {comparisons.length>0&&<div className="catalogue-compare-tray" role="region" aria-label="Product comparison selection"><div className="catalogue-compare-thumbs">{comparisons.map(product=><div key={product.id}><img src={product.image} alt={productTitle(product)}/><button aria-label={`Remove ${productTitle(product)} from comparison`} onClick={()=>toggleCompare(product)}><X size={11}/></button></div>)}</div><div><strong>{comparisons.length} of 3 selected</strong><small>Compare products, uses & recorded packs</small></div><Button disabled={comparisons.length<2} onClick={()=>setPanel('compare')} icon={Layers3}>Compare products</Button><button className="icon-button" aria-label="Clear product comparison" onClick={()=>setCompareIds([])}><X size={18}/></button></div>}

    {selected&&<ProductDetails key={selected.id} product={selected} matchCount={matches[selected.id]} saved={sampleIds.includes(selected.id)} onSample={()=>toggleSample(selected)} onBuyers={()=>showBuyers(selected)} onClose={()=>updateRoute({item:null})}/>}
    {panel==='compare'&&<Modal title="Compare your product selection" subtitle="Different products serve different recipes. Trial them with the buyer before recommending a replacement." onClose={()=>setPanel(null)} wide><div className="catalogue-comparison-scroll"><table className="catalogue-comparison-table"><caption className="sr-only">Product comparison by pack, retail snapshot, uses and buyer categories</caption><thead><tr><th scope="col">At a glance</th>{comparisons.map(product=><th scope="col" key={product.id}><img src={product.image} alt=""/><button onClick={()=>showProduct(product)}>{productTitle(product)}<ArrowUpRight size={13}/></button></th>)}</tr></thead><tbody>{[
      ['Recorded pack', (product:Product)=>productPack(product)],
      ['Retail snapshot',(product:Product)=>`${currency(product.price,false)} · ${snapshotDate(product)}`],
      ['Suggested uses',(product:Product)=>productBrief(product).uses.join(' · ')],
      ['Buyer categories',(product:Product)=>product.segments.join(' · ')],
      ['Category-fit prospects',(product:Product)=>String(matches[product.id])],
    ].map(([label,render])=><tr key={label as string}><th scope="row">{label as string}</th>{comparisons.map(product=><td key={product.id}>{(render as (product:Product)=>string)(product)}</td>)}</tr>)}<tr><th scope="row">Sample planning</th>{comparisons.map(product=><td key={product.id}><Button variant="secondary" icon={sampleIds.includes(product.id)?Check:Bookmark} onClick={()=>toggleSample(product)}>{sampleIds.includes(product.id)?'In sample list':'Add to sample list'}</Button></td>)}</tr><tr><th scope="row">Official source</th>{comparisons.map(product=><td key={product.id}><a className="text-link" href={product.url} target="_blank" rel="noreferrer">View product <ExternalLink size={13}/></a></td>)}</tr></tbody></table></div><div className="catalogue-modal-note">Retail references cover the recorded packs, which may differ in size. They are not a comparison of wholesale prices or cost per serving.</div></Modal>}
    {panel==='samples'&&<Modal title="Your sample list" subtitle={storageAvailable?'Saved in this browser only. No order or sample request has been sent.':'Kept for this session only; browser storage is unavailable.'} onClose={()=>setPanel(null)} wide>{samples.length?<><div className="catalogue-sample-list">{samples.map(product=><article key={product.id}><button onClick={()=>showProduct(product)}><img src={product.image} alt=""/><span><strong>{productTitle(product)}</strong><small>{product.category} · recorded pack: {productPack(product)}</small><span>{productBrief(product).uses.slice(0,2).join(' · ')}</span></span></button><button className="icon-button" aria-label={`Remove ${productTitle(product)} from sample list`} onClick={()=>toggleSample(product)}><X size={17}/></button></article>)}</div><div className="catalogue-sample-checklist"><strong>Before requesting samples</strong><p>Confirm the buyer’s recipe, preferred trial quantity, pack size and delivery address. Your selection is a conversation aid, not a purchase order.</p></div><div className="modal-footer"><span className="muted">{samples.length} products selected</span><Button icon={Download} onClick={downloadSelection}>Download selection</Button></div></>:<EmptyState icon={Bookmark} title="Make it a thoughtful first sample" text="Use the bookmark on any product to build a selection for your buyer conversation. It stays in this browser." action={<Button onClick={()=>setPanel(null)}>Explore products <ArrowRight size={15}/></Button>}/>}</Modal>}
  </div>;
}

function ProductDetails({product,matchCount,saved,onSample,onBuyers,onClose}:{product:Product;matchCount:number;saved:boolean;onSample:()=>void;onBuyers:()=>void;onClose:()=>void}){
  const {notify,mode}=useApp();const variants=productVariants(product);const [variantId,setVariantId]=useState(variants[0].id);const variant=variants.find(item=>item.id===variantId)||variants[0];
  const pack=variant.title==='Default Title'?productPack(product):variant.title;const brief=productBrief(product);
  const copy=async()=>{
    const text=[product.name,`Category: ${product.category}`,`Recorded pack: ${pack}`,`Retail snapshot: ${currency(variant.price,false)} on ${snapshotDate(product)}. Not a B2B quote.`,product.pitch,`Suggested uses (confirm with buyer): ${brief.uses.join(', ')}`,`Suggested buyer categories: ${product.segments.join(', ')}`,`Ask: ${brief.question}`,`Official source: ${product.url}`,'Confirm sample size, MOQ, stock, lead time and trade pricing before making a commitment.'].join('\n');
    try{await navigator.clipboard.writeText(text);notify('Product brief copied with source and price context.');}catch{notify('Clipboard is unavailable. You can select and copy the product details.','error');}
  };
  return <Modal title={productTitle(product)} subtitle={product.category} onClose={onClose} wide><div className="catalogue-product-detail"><div className="catalogue-detail-media"><img src={product.image} alt={product.name}/><span><ShieldCheck size={14}/>Official catalogue imagery</span><a href={product.url} target="_blank" rel="noreferrer">Open product source <ExternalLink size={14}/></a></div><div className="catalogue-detail-content"><span className="eyebrow">THE PRODUCT BRIEF</span><h3>{productTitle(product)}</h3><p className="catalogue-detail-pitch">{product.pitch}</p><div className="catalogue-detail-price"><span>RECORDED RETAIL REFERENCE</span><strong>{currency(variant.price,false)}</strong>{variants.length>1?<label>Pack / variant<select aria-label="Product pack variant" value={variantId} onChange={event=>setVariantId(event.target.value)}>{variants.map(item=><option key={item.id} value={item.id}>{item.title==='Default Title'?productPack(product):item.title}</option>)}</select></label>:<p><Package size={15}/>{pack}</p>}<small>Snapshot: {snapshotDate(product)}. Not a B2B quote.</small>{variant.available!==undefined&&<small>{variant.available?'Listed available':'Listed unavailable'} at last sync; check current stock.</small>}</div><div className="catalogue-detail-section"><h4>Where it could fit</h4><div className="catalogue-detail-uses">{brief.uses.map(use=><span key={use}><Check size={13}/>{use}</span>)}</div><p>Suggested applications. Confirm suitability through a recipe or service trial.</p></div><div className="catalogue-detail-section"><h4>Suggested buyer categories</h4><div className="product-buyer-tags">{product.segments.map(segment=><Badge key={segment} tone="gray">{segment}</Badge>)}</div></div></div></div><div className="catalogue-buyer-question"><Coffee size={23}/><div><span className="eyebrow">START THE CONVERSATION</span><p>“{brief.question}”</p></div></div><details className="catalogue-source-details"><summary>Published title, source & trade details to confirm</summary><dl><div><dt>Official product title</dt><dd>{product.name}</dd></div><div><dt>Recorded variant / pack</dt><dd>{pack}. The recorded variant takes precedence over pack wording in the product title.</dd></div><div><dt>Wholesale details</dt><dd>MOQ, trade price, sample quantity, stock and delivery terms are not confirmed in this snapshot.</dd></div><div><dt>Source</dt><dd><a href={product.url} target="_blank" rel="noreferrer">Dhampur Green product page <ExternalLink size={12}/></a></dd></div></dl></details><div className="catalogue-detail-actions"><Button variant="secondary" icon={saved?Check:Bookmark} onClick={onSample}>{saved?'In sample list':'Add to sample list'}</Button><Button variant="secondary" icon={Copy} onClick={()=>void copy()}>Copy product brief</Button><Button icon={ArrowUpRight} onClick={onBuyers}>Explore {matchCount} {mode==='demo'?'sample':'category-fit'} prospects</Button></div></Modal>;
}
