import { useEffect, useState } from 'react';
import { ArrowRight, BookOpen, Check, Database, ExternalLink, RefreshCw, Search, ShieldCheck, Sparkles } from 'lucide-react';
import type { DataReport, Job, Lead } from '../shared/types';
import { api, Badge, Button, PageHeading, useApp } from './lib';

export function DataQuality(){
  const {data,mode,navigate,run,openLead}=useApp();const [report,setReport]=useState<DataReport|null>(null);const [error,setError]=useState('');const [city,setCity]=useState('All cities');const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;api<DataReport>('/data-quality').then(result=>{if(active){setReport(result);setError('');}}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[data.leads.length,data.jobs]);
  if(!report)return <div className="inline-note">{error||'Loading source coverage…'}</div>;
  const sources=report.sources.filter(source=>city==='All cities'||source.city===city);
  const reviewing=data.leads.filter(lead=>lead.researchCheck?.changes.length);
  const active=data.jobs.some(job=>job.mode==='live'&&['queued','running'].includes(job.status));
  return <><PageHeading eyebrow="KNOW WHAT YOU KNOW" title="Data & accuracy" description="Published business facts, clear gaps, and suggestions you can check."><Button variant="secondary" icon={BookOpen} onClick={()=>navigate('How it works')}>How it works</Button></PageHeading>
    <section className="data-hero"><div><Badge tone="sand"><ShieldCheck size={13}/> SOURCE FIRST</Badge><h2>More useful leads.<br/><em>Every fact has a starting point.</em></h2><p>Official websites provide the business details. Your catalogue guides product matches. The buyer confirms purchasing needs.</p></div><div className="data-hero-numbers"><strong>{report.total}</strong><span>real business locations</span><small>{report.brands} brands / independent businesses<br/>Branch counts are not separate buying teams.</small></div></section>
    <div className="data-metrics">{[[report.withEvidence,'Have linked evidence','Published facts, not purchasing confirmation'],[report.withPhone,'Have a phone',`${report.uniquePhones} distinct numbers; roles unconfirmed`],[report.withEmail,'Have an email',`${report.uniqueEmails} distinct addresses; deliverability untested`],[report.needsReview,'Have source differences','Review before changing your CRM record']].map(([value,label,detail])=><article className="card" key={label}><strong>{value}</strong><h3>{label}</h3><p>{detail}</p></article>)}</div>
    <section className="card data-refresh"><div className="section-heading"><div><span className="eyebrow">GROW YOUR RESEARCH LIST</span><h2>Refresh official directories</h2><p>One refresh checks supported sources, adds new branches and keeps your notes and sales stages.</p></div><Database size={25}/></div><div className="data-refresh-actions"><label>Market<select aria-label="Research market" value={city} onChange={e=>setCity(e.target.value)}><option>All cities</option>{report.byCity.map(item=><option key={item.city}>{item.city}</option>)}</select></label><Button requiresWrite icon={RefreshCw} busy={busy} disabled={active||!sources.length} onClick={async()=>{setBusy(true);await run(()=>api<Job>('/discover',{cities:[...new Set(sources.map(s=>s.city))],segments:[...new Set(sources.map(s=>s.segment))],limit:500,mode:'live'}),'Research queued. Follow progress in Automations.');setBusy(false);}}>{active?'Refresh in progress':'Check sources & add up to 500'}</Button><button className="text-link" onClick={()=>navigate('Automations')}>Set a daily routine <ArrowRight size={14}/></button></div><p className="small muted">No API key needed. Each directory is fetched at most once per 24 hours. New additions depend on published locations; 500 is a limit, not a promised result. Coverage currently focuses on cafés and bakeries.</p>{mode==='demo'&&<div className="inline-note">This report and refresh apply to the real business workspace.</div>}
      <div className="source-directory-list">{sources.map(source=><article key={source.id}><div><strong>{source.name}</strong><span>{source.city} · {source.segment}</span></div><div>{source.status?.error?<Badge tone="sand">Needs attention</Badge>:source.status?.checkedAt?<Badge>Checked {new Date(source.status.checkedAt).toLocaleDateString('en-IN')}</Badge>:<Badge tone="gray">Ready to refresh</Badge>}<a className="text-link" href={source.url} target="_blank" rel="noreferrer" aria-label={`Open ${source.name} source`}>Source <ExternalLink size={13}/></a></div>{source.status?.error&&<p className="form-error">{source.status.error}</p>}</article>)}</div>{!sources.length&&<p>No connector covers this city yet. Import independently sourced businesses by CSV.</p>}</section>
    <div className="data-bottom-grid"><section className="card data-coverage"><span className="eyebrow">COVERAGE, NOT MARKET SIZE</span><h2>Where the data is strongest</h2><p>These are workspace counts. Empty categories are research gaps.</p>{report.bySegment.map(item=><div className="coverage-row" key={item.segment}><span>{item.segment}</span><div><i style={{width:`${report.total?item.count/report.total*100:0}%`}}/></div><strong>{item.count}</strong></div>)}<p className="small muted">{report.stale} records have missing evidence or at least one fact last checked over 90 days ago. Refreshing a page does not validate every stored contact.</p></section><section className="card data-tools"><span className="eyebrow">GOOGLE + AI, WITH CLEAR ROLES</span><h2>What each tool does</h2><article><Search size={20}/><div><h3>Google checks a current listing <Badge tone={report.google.configured?'green':'sand'}>{report.google.configured?'Key configured':'Key needed'}</Badge></h3><p>Open a lead → Sources → Check Google listing. Compare possible matches yourself. Results stay in that view and are not added to the database or AI input.</p><small>{report.google.used} / {report.google.limit} requests today (UTC)</small></div></article><article><Sparkles size={20}/><div><h3>AI writes from supplied evidence <Badge tone={report.ai.configured?'green':'sand'}>{report.ai.configured?'Key configured':'Templates active'}</Badge></h3><p>Your catalogue and linked business facts are supplied with each request. This is evidence-based prompting, not model training. AI suggestions still need review.</p><small>{report.ai.used} / {report.ai.limit} requests today (UTC)</small></div></article><article><Check size={20}/><div><h3>The buyer confirms actual demand</h3><p>Monthly quantities are planning scenarios until confirmed. Public phone numbers and emails do not prove a purchasing role or consent to receive marketing.</p></div></article><Button variant="secondary" onClick={()=>navigate('Settings')}>Manage connections <ArrowRight size={14}/></Button></section></div>
    {reviewing.length>0&&<section className="card data-review"><h2>Check these source differences</h2><p>Published information differs from your saved record. Open Sources to compare and choose which changes to accept.</p>{reviewing.slice(0,8).map(lead=><button key={lead.id} onClick={()=>openLead(lead)}><span><strong>{lead.name}</strong><small>{lead.city} · {lead.researchCheck!.changes.length} differences</small></span><ArrowRight size={16}/></button>)}</section>}
  </>;
}

type GoogleResult={places:{id:string;displayName?:{text:string};formattedAddress?:string;internationalPhoneNumber?:string;googleMapsUri?:string;businessStatus?:string;attributions?:{provider?:string;providerUri?:string}[]}[];checkedAt:string};
export function GoogleCheck({lead}:{lead:Lead}){
  const {run,data,navigate}=useApp();const [result,setResult]=useState<GoogleResult|null>(null);const [busy,setBusy]=useState(false);
  const configured=data.integrations.find(item=>item.id==='google')?.configured;
  return <section className="google-check"><h3>Compare a current Google listing</h3><p>A possible match is not confirmation. Check the branch and address. This lookup does not update the saved lead.</p><Button requiresWrite variant="secondary" icon={Search} busy={busy} disabled={lead.demo} onClick={async()=>{if(!configured){navigate('Settings');return;}setBusy(true);const response=await run(()=>api<GoogleResult>(`/leads/${lead.id}/google-check`,{}));setResult(response??null);setBusy(false);}}>Check Google listing</Button>{!configured&&<small>Add GOOGLE_PLACES_API_KEY in server settings to enable live checks.</small>}{result&&<div className="google-results"><p className="google-attribution" translate="no">Google Maps</p>{result.places.length?result.places.map(place=><article key={place.id}><strong>{place.displayName?.text||'Unnamed listing'}</strong><p>{place.formattedAddress||'Address unavailable'}</p><small>{place.internationalPhoneNumber||'Phone unavailable'} · {place.businessStatus?.replaceAll('_',' ').toLowerCase()||'Status unavailable'}</small>{place.googleMapsUri&&/^https:\/\//.test(place.googleMapsUri)&&<a href={place.googleMapsUri} target="_blank" rel="noreferrer">View in Google Maps <ExternalLink size={13}/></a>}{place.attributions?.map((attribution,index)=><p key={index}>{attribution.providerUri&&/^https:\/\//.test(attribution.providerUri)?<a href={attribution.providerUri} target="_blank" rel="noreferrer">{attribution.provider||'Data provider'}</a>:attribution.provider}</p>)}</article>):<p>No matching listing returned. Your saved record is unchanged.</p>}<small>Retrieved {new Date(result.checkedAt).toLocaleString('en-IN')} · displayed only in this view</small></div>}</section>;
}
