import { useState } from 'react';
import { ArrowRight, Search, Package, MessageCircle, Send, CalendarCheck, Check, Sparkles, BookOpen, Zap } from 'lucide-react';
import { Badge, Button, PageHeading, type Page, useApp } from './lib';

const steps=[
  {title:'Find the right businesses',short:'Find',icon:Search,page:'Discover leads' as Page,action:'Browse businesses',auto:'Keeps public business details, source links and product matches together. Official-directory refreshes add more supported locations without API keys.',you:'Choose a city and buyer type. Open a business and check the source.',result:'A business worth speaking to'},
  {title:'Understand the product opportunity',short:'Match',icon:Package,page:'Saved leads' as Page,action:'Open your shortlist',auto:'Suggests uses for your products and calculates a quantity range from visible assumptions.',you:'Open Product opportunity in a lead. Adjust quantities and save your scenario. Actual demand is unknown until the buyer confirms it.',result:'Relevant products and a starting estimate'},
  {title:'Speak to the right person',short:'Confirm',icon:MessageCircle,page:'Today' as Page,action:'Open today’s actions',auto:'Shows available business contacts and suggested questions. Keeps your call notes and next date together.',you:'Ask for purchasing, confirm their current product and monthly use, and check whether buying is handled centrally.',result:'A real requirement and the right contact'},
  {title:'Prepare an introduction or sample',short:'Introduce',icon:Send,page:'Outreach studio' as Page,action:'Review outreach',auto:'Creates an introduction using a template, or AI when connected. Stores the draft for your review.',you:'Check the recipient and message. Agree on a sample and quote. Email sends only after your review and a sending service is connected.',result:'A clear proposal for the buyer'},
  {title:'Follow up and record the outcome',short:'Follow up',icon:CalendarCheck,page:'Sales pipeline' as Page,action:'View sales pipeline',auto:'Brings scheduled follow-ups into Today and keeps the conversation history.',you:'Log the response, move the sales stage and agree the next action. Mark Won only when the order is confirmed.',result:'A clear next step or a confirmed customer'},
];
export function Guide(){
  const {data,navigate,mode}=useApp();const [active,setActive]=useState(0);const step=steps[active];const Icon=step.icon;

  const ai=data.integrations.find(i=>i.id==='openai')?.configured;
  return <><PageHeading eyebrow="THE SIMPLE GUIDE" title="From a business to a buyer." description="Five small steps. One place to manage the whole conversation."><Button icon={Search} onClick={()=>navigate('Discover leads')}>Start with a business</Button></PageHeading>
    <section className="guide-hero"><div><Badge tone="sand"><BookOpen size={13}/> HOW GROW WORKS</Badge><h2>You build the relationship.<br/><em>Grow organises the work.</em></h2><p>Find a café, restaurant or hotel. Understand where your products fit. Confirm what they need, make an introduction, and follow up.</p></div><div className="guide-outcome"><span>YOUR STARTING POINT</span><strong>{data.leads.length}</strong><p>{mode==='demo'?'sample business records':'real business locations'} in this workspace</p><small>Locations are prospects, not confirmed customers.</small></div></section>
    <section className="guide-walkthrough" aria-label="Interactive workflow guide"><div className="workflow-track" role="tablist" aria-label="Sales workflow steps">{steps.map((s,i)=><button key={s.short} id={`workflow-tab-${i}`} role="tab" aria-selected={active===i} aria-controls="workflow-panel" tabIndex={active===i?0:-1} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?4:(active+(e.key==='ArrowRight'?1:4))%5;setActive(next);document.getElementById(`workflow-tab-${next}`)?.focus();}}} onClick={()=>setActive(i)}><span>{i+1}</span><strong>{s.short}</strong>{i<4&&<ArrowRight size={16}/>}</button>)}</div><div id="workflow-panel" className="workflow-panel" role="tabpanel" aria-labelledby={`workflow-tab-${active}`}><div className="workflow-panel-title"><span><Icon size={26}/></span><div><small>STEP {active+1} OF 5</small><h2>{step.title}</h2></div></div><div className="workflow-responsibilities"><article><span><Sparkles size={16}/> WHAT GROW DOES</span><p>{step.auto}</p></article><article><span><Check size={16}/> WHAT YOU DO</span><p>{step.you}</p></article></div><div className="workflow-result"><p><strong>You finish with</strong>{step.result}</p><Button variant="secondary" icon={ArrowRight} onClick={()=>navigate(step.page)}>{step.action}</Button></div><div className="guide-step-controls"><button disabled={active===0} className="text-link" onClick={()=>setActive(active-1)}>Previous step</button><button disabled={active===4} className="text-link" onClick={()=>setActive(active+1)}>Next step <ArrowRight size={14}/></button></div></div></section>
    <div className="guide-bottom-grid"><section className="card guide-example"><span className="eyebrow">AN EASY EXAMPLE</span><h3>A café and a box of sachets.</h3><div className="example-equation"><span><strong>80</strong>eligible drinks / day</span><b>×</b><span><strong>30</strong>service days</span><b>=</b><span><strong>2,400</strong>sachets / month</span></div><p>Assuming one sachet per drink and all of those sachets supplied by you. This is a made-up planning example. Ask the café for its actual usage and the share it wants to trial.</p><p>Start with a sample of the preferred sugar, confirm the price and delivery schedule, then set a follow-up date.</p></section><section className="card guide-automation"><span className="eyebrow"><Zap size={14}/> MAKE IT MOSTLY AUTOMATIC</span><h3>Start small. Add automation.</h3><ul><li><Check size={16}/><div><strong>Ready now</strong><p>Browse sourced records, match products, estimate needs, save notes and track follow-ups.</p></div></li><li><span className="connection-dot"/><div><strong>Scheduled business discovery <Badge tone="green">No key needed</Badge></strong><p>Official directories provide café and bakery locations in supported cities. Set a routine in Automations; check coverage in Data & accuracy.</p></div></li><li><span className="connection-dot"/><div><strong>AI-written introductions <Badge tone={ai?'green':'sand'}>{ai?'Key configured':'Optional'}</Badge></strong><p>Connect OpenAI for draft writing. Templates work without it. Your team reviews every send.</p></div></li></ul><button className="text-link" onClick={()=>navigate('Settings')}>See connections & setup <ArrowRight size={14}/></button></section></div>
  </>;
}
