import { ResearchOverview } from './ResearchTools';
import { useState } from 'react';
import { Search, ArrowUpRight, ArrowRight, Users, Target, Sparkles, MapPin, Coffee, Hotel, UtensilsCrossed, Croissant, Download, Check, CalendarDays, Mail, Bookmark, Globe, CircleCheck, Workflow, Phone, ChevronRight, Building2 } from 'lucide-react';
import { Avatar, Badge, Button, CardHeading, currency, EmptyState, PageHeading, Score, TextLink, useApp } from './lib';
import { GrowthChart } from './charts';
import { GettingStarted } from './Today';
import { businessDate, followUpState } from '../shared/workflow';
import type { Lead } from '../shared/types';

export function LeadTable({leads,compact=false,selected,onSelect}:{leads:Lead[];compact?:boolean;selected?:Set<string>;onSelect?:(id:string)=>void}) {
  const {openLead,data}=useApp();
  return <div className="table-scroll"><table className={`leads-table ${compact?'compact':''}`}><thead><tr>
    {onSelect&&<th className="checkbox-cell"><span className="sr-only">Select</span></th>}<th>Business</th><th className="location-column">Location</th><th className="fit-column">Suggested product</th><th>Fit score</th>{!compact&&<th className="stage-column">Stage</th>}<th className="end-cell"/>
  </tr></thead><tbody>{leads.map(lead=><tr key={lead.id} onClick={()=>openLead(lead)}>
    {onSelect&&<td className="checkbox-cell" onClick={e=>e.stopPropagation()}><input type="checkbox" aria-label={`Select ${lead.name}`} checked={selected?.has(lead.id)??false} onChange={()=>onSelect(lead.id)}/></td>}
    <td><button className="business-cell" onClick={e=>{e.stopPropagation();openLead(lead);}}><Avatar name={lead.name} segment={lead.segment}/><span><strong>{lead.name}</strong><small>{lead.segment}<span className="mobile-lead-city"> · {lead.city}</span></small><span className={`record-source ${lead.demo?'sample':''}`}><Globe size={11}/>{lead.demo?'Sample business':lead.source==='Official business website'?'Official website':lead.source}<span className="contact-dots" title="Available contacts">{lead.phone&&<Phone size={11}/>} {lead.email&&<Mail size={11}/>}</span></span></span></button></td>
    <td className="location-column"><span className="location-cell">{lead.city}<small title={lead.area}>{lead.area.length>32?lead.area.slice(0,32)+'…':lead.area}</small></span></td>
    <td className="fit-column"><span className="product-fit-tag">{data.products.find(p=>p.id===lead.products[0])?.category??'Review fit'}</span>{lead.products.length>1&&<span className="more-tag">+{lead.products.length-1}</span>}</td><td><Score value={lead.score}/></td>
    {!compact&&<td className="stage-column"><Badge tone={lead.stage==='New'?'blue':lead.stage==='Won'?'green':lead.stage==='Lost'?'gray':'sand'}>{lead.stage}</Badge></td>}
    <td><button className="icon-button row-open" aria-label={`Open ${lead.name}`} onClick={e=>{e.stopPropagation();openLead(lead);}}><ArrowUpRight size={17}/></button></td>
  </tr>)}</tbody></table></div>;
}
function Stats({leads}:{leads:Lead[]}) {
  const today=businessDate();
  const {data}=useApp();
  const stats=data.readOnly?[
    {label:'Business locations',value:leads.length,icon:Building2,sub:'Researched prospects · not confirmed buyers'},
    {label:'Markets covered',value:new Set(leads.map(l=>l.city)).size,icon:MapPin,sub:'Start with Delhi NCR, Mumbai and Bengaluru'},
    {label:'With a public phone',value:leads.filter(l=>l.phone).length,icon:Phone,sub:'Locations · purchasing roles unconfirmed'},
    {label:'With a public email',value:leads.filter(l=>l.email).length,icon:Mail,sub:'Locations · deliverability untested'},
  ]:[
    {label:'Business locations',value:leads.length,icon:Building2,sub:`${new Set(leads.map(l=>l.city)).size} cities · branches counted separately`},
    {label:'On your shortlist',value:leads.filter(l=>l.saved).length,icon:Bookmark,sub:'Prospects saved by your team'},
    {label:'Contacted',value:leads.filter(l=>['Contacted','Sample sent','Negotiation','Won'].includes(l.stage)).length,icon:Mail,sub:'Based on your sales stages'},
    {label:'Follow-ups due',value:leads.filter(l=>l.nextFollowUp&&l.nextFollowUp<=today&&!['Won','Lost'].includes(l.stage)&&!l.suppressed).length,icon:CalendarDays,sub:'Today or overdue · open prospects'},
  ];
  return <div className="stats-grid">{stats.map(s=><div className="stat-card" key={s.label}><div className="stat-top"><span>{s.label}</span><span className="stat-icon"><s.icon size={19}/></span></div><div className="stat-main"><strong>{s.value}</strong></div><div className="stat-caption">{s.sub}</div></div>)}</div>;
}
export function Overview() {
  const {data,mode,navigate,discover,browse,openLead}=useApp();
  const [market,setMarket]=useState('All cities');
  const prospects=data.leads.filter(l=>!['Won','Lost'].includes(l.stage)&&!l.suppressed);
  const prioritized=prospects.filter(l=>market==='All cities'||l.city===market).sort((a,b)=>Number(a.stage!=='New')-Number(b.stage!=='New')||b.score-a.score).slice(0,4);
  const newLeads=prospects.filter(l=>l.stage==='New');
  const followUps=prospects.filter(l=>l.nextFollowUp).sort((a,b)=>a.nextFollowUp.localeCompare(b.nextFollowUp)).slice(0,3);
  const sourceCount=data.leads.filter(l=>l.sourceUrl&&!l.demo).length;
  const emailCount=data.leads.filter(l=>l.email).length;
  const google=data.integrations.find(i=>i.id==='google')?.configured;
  const categories=[{name:'Cafés',icon:Coffee,copy:'Sugar sachets & beverage sweeteners',color:'coffee'},{name:'Restaurants',icon:UtensilsCrossed,copy:'Jaggery, specialty sugars & syrups',color:'restaurant'},{name:'Hotels & resorts',icon:Hotel,copy:'Breakfast service & in-room sachets',color:'hotel'},{name:'Bakeries',icon:Croissant,copy:'Baking sugars & dessert ingredients',color:'bakery'}];
  return <>
    <div className="overview-heading"><div><div className="eyebrow"><span className="live-dot"/> DHAMPUR GREEN / HOSPITALITY SALES</div><h1>Your next customer<br/><em>starts with a connection.</em></h1><p>Find the right businesses. Start a conversation. Grow your sales.</p></div><div className="heading-actions"><Button icon={Search} onClick={()=>mode==='live'&&!google?browse():discover()}>{mode==='live'&&!google?'Browse businesses':'Find more businesses'} <ArrowUpRight size={16}/></Button></div></div>

    {data.readOnly?<ResearchOverview/>:<><div className="daily-entry"><div><CalendarDays size={20}/><span><strong>Your daily work, in one place.</strong><small>Review follow-ups, log calls and plan your next conversation.</small></span></div><Button variant="secondary" onClick={()=>navigate('Today')}>Open today’s actions <ArrowRight size={15}/></Button></div><GettingStarted/><button className="guide-shortcut" onClick={()=>navigate('How it works')}><span><strong>New here? See the simple workflow.</strong><small>Find → Match products → Confirm needs → Introduce → Follow up</small></span><ArrowRight size={20}/></button></>}<Stats leads={data.leads}/>
    <div className="workspace-focus"><section className="today-card"><span className="eyebrow">YOUR NEXT MOVE</span><h2>{newLeads.length?'A good prospect deserves a closer look.':'Keep your conversations moving.'}</h2><p>{newLeads.length?<>You have <strong>{newLeads.length} businesses to review</strong>. Start with their public details and the Dhampur Green products that suit their category.</>:'Review your sales pipeline and schedule the next step for each open opportunity.'}</p><div><Button onClick={()=>newLeads[0]?openLead(newLeads[0]):navigate('Sales pipeline')} icon={newLeads.length?Target:CalendarDays}>{newLeads.length?'Review a business':'Open sales pipeline'}<ArrowRight size={16}/></Button><span>{mode==='demo'?'Practice with sample data':'Public facts. Your judgement.'}</span></div><div className="focus-art" aria-hidden="true"><div className="art-ring"/><div className="art-card"><LeafMark/><span>dhampur green</span><strong>Good products.<br/>The right buyers.</strong><div><Coffee size={18}/><UtensilsCrossed size={18}/><Hotel size={18}/></div></div></div></section>
    <section className="card source-health"><div className="source-health-heading"><span className="source-icon"><Globe size={21}/></span><div><h3>Know your data</h3><p>{mode==='demo'?'Sample workspace':'Your real business workspace'}</p></div></div><dl><div><dt>Records with source links</dt><dd>{sourceCount}<small> / {data.leads.length}</small></dd></div><div><dt>Locations with an email</dt><dd>{emailCount}</dd></div><div><dt>Product catalogue</dt><dd>{data.products.length}<small> products</small></dd></div></dl><p className="health-note">{mode==='demo'?'Fictional leads for exploring the workflow.':<>Sources appear in every profile. Emails may be for reservations or general enquiries; purchasing roles need confirmation.</>}</p></section></div>
    <section className="market-section"><div className="section-title-row"><div><span className="eyebrow">START LOCAL</span><h2>Your priority markets</h2></div><TextLink onClick={()=>browse()}>Browse all businesses</TextLink></div><div className="market-cards">{['Delhi NCR','Mumbai','Bengaluru'].map((city,i)=><button className={`market-card market-${i}`} key={city} onClick={()=>browse(city)}><span className="market-symbol"><MapPin size={22}/><span>0{i+1}</span></span><div><strong>{city}</strong><p>{data.leads.filter(l=>l.city===city).length} business locations</p><small>{data.leads.filter(l=>l.city===city&&l.phone).length} with phone · {data.leads.filter(l=>l.city===city&&l.email).length} with email</small></div><ArrowUpRight size={20}/></button>)}</div></section>
    <div className="dashboard-bottom"><section className="card priority-card"><CardHeading title="Businesses to review" subtitle="Sorted by review status and estimated product fit."><select className="small-select" aria-label="Overview city filter" value={market} onChange={e=>setMarket(e.target.value)}><option>All cities</option>{data.settings.targetCities.map(city=><option key={city}>{city}</option>)}</select></CardHeading>{prioritized.length?<LeadTable leads={prioritized} compact/>:<EmptyState title="No open prospects in this market" text="Browse your directory or discover more businesses." action={<Button onClick={()=>browse(market==='All cities'?undefined:market)}>Browse businesses</Button>}/>}<div className="table-footnote"><Target size={14}/><span>Fit scores prioritize research. They do not indicate buying interest.</span><TextLink onClick={()=>browse(market==='All cities'?undefined:market)}>View all</TextLink></div></section><section className="card segment-card"><CardHeading title="Match products to buyers" subtitle="Suggested uses from your product catalogue."/><div className="segment-list">{categories.map(c=><button key={c.name} onClick={()=>browse(undefined,c.name)}><span className={`segment-icon ${c.color}`}><c.icon size={22}/></span><span><strong>{c.name}</strong><small>{c.copy}</small></span><ChevronRight size={16}/></button>)}</div><button className="all-segments" onClick={()=>navigate('Product catalogue')}>Explore your catalogue <ArrowRight size={15}/></button></section></div>
    <div className="overview-final-row"><section className="card follow-up-card"><CardHeading title="Upcoming follow-ups" subtitle="Dates set by your team."/><div className="follow-up-list">{followUps.length?followUps.map(lead=><button key={lead.id} onClick={()=>openLead(lead)}><span className="follow-date">{new Date(lead.nextFollowUp+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span><span><strong>{lead.name}</strong><small>{lead.stage} · {lead.city}</small></span><ArrowUpRight size={17}/></button>):<div className="follow-up-empty"><CalendarDays size={25}/><div><strong>No follow-ups scheduled yet</strong><p>Open a business → Relationship → set the next follow-up date.</p></div></div>}</div></section><section className="automation-invite"><span className="routine-icon"><Workflow size={23}/></span><div><Badge tone="light">READY TO CONFIGURE</Badge><h3>Make finding leads a daily habit.</h3><p>Set a daily or weekly official-directory refresh. Check supported cities and buyer categories in Data & accuracy.</p><TextLink onClick={()=>navigate(data.readOnly?'Settings':'Automations')}>{data.readOnly?'See setup steps':'Create a routine'}</TextLink></div></section></div>
  </>;
}
function LeafMark(){return <span className="leaf-mark"><Sparkles size={24}/></span>;}
export function Reports(){
  const {data,mode,navigate}=useApp();const [days,setDays]=useState(30);const [conversion,setConversion]=useState(10);const [averageOrder,setAverageOrder]=useState(data.settings.defaultDealValue);
  const cityData=data.settings.targetCities.map(city=>({city,leads:data.leads.filter(l=>l.city===city)}));
  return <><PageHeading eyebrow="MEASURE YOUR PROGRESS" title="Reports" description="Understand your markets, product fit, and sales progress."><a className="button secondary" href={`/api/leads/export?mode=${mode}`}><Download size={16}/>Export lead data</a></PageHeading><Stats leads={data.leads}/><section className="card report-chart"><CardHeading title="Lead base over time" subtitle="Cumulative records by creation date, using your current fit scores."><select className="small-select" aria-label="Report period" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={14}>Last 14 days</option><option value={30}>Last 30 days</option></select></CardHeading><GrowthChart leads={data.leads} days={days}/></section><div className="two-columns"><section className="card"><CardHeading title="Market performance" subtitle="Use high-fit concentration to prioritize your next search."/><div className="market-report">{cityData.map(({city,leads})=><div key={city}><div><strong>{city}</strong><span>{leads.length} leads · {leads.filter(l=>l.score>=80).length} high fit</span></div><div className="progress-track"><span style={{width:`${data.leads.length?leads.length/data.leads.length*100:0}%`}}/></div></div>)}</div></section><section className="card"><CardHeading title="Product demand signals" subtitle="Category matches across leads, not confirmed buyer demand."/><div className="product-report">{data.products.map(p=>({...p,count:data.leads.filter(l=>l.products.includes(p.id)).length})).sort((a,b)=>b.count-a.count).slice(0,5).map(p=><div key={p.id}><span>{p.name}</span><strong>{p.count}<small> matches</small></strong></div>)}</div></section></div><section className="card planning-card"><CardHeading title="Plan your next month" subtitle="An adjustable scenario to help set activity targets. This is not a revenue forecast."/><div className="planning-grid"><label>Assumed lead-to-customer conversion<input type="range" min={1} max={50} value={conversion} onChange={e=>setConversion(Number(e.target.value))}/><strong>{conversion}%</strong></label><label>Assumed monthly order per customer (₹)<input type="number" min={0} max={10000000} value={averageOrder} onChange={e=>setAverageOrder(Math.max(0,Number(e.target.value)))}/></label><div><span>Scenario monthly sales</span><strong>{currency(data.leads.length*conversion/100*averageOrder)}</strong><small>{data.leads.length} leads × {conversion}% × {currency(averageOrder)}</small></div><div><span>Customers to reach your target</span><strong>{averageOrder>0?Math.ceil(data.settings.monthlyTarget/averageOrder):'—'}</strong><small>Target: {currency(data.settings.monthlyTarget)} / month</small></div></div></section><div className="inline-note"><Target size={17}/><p>Opportunity values are manually entered estimates. Won value represents deals marked won, and does not track invoicing or payments. Use your accounting system to confirm collected revenue.</p></div></>;
}
