import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCircle2, Circle, Clock, Mail, MapPin, Phone, Search, Target } from 'lucide-react';
import { contactOutcomes, stages, type ContactLog, type Lead, type Stage, type Readiness } from '../shared/types';
import { businessDate, dateAfter, followUpState, isOpenLead } from '../shared/workflow';
import { api, Avatar, Badge, Button, CardHeading, EmptyState, Modal, PageHeading, useApp } from './lib';

export function Today() {
  const {data,openLead,logContact,navigate,browse,openDraft}=useApp();
  const [tab,setTab]=useState<'due'|'upcoming'|'review'|'drafts'>('due');
  const [city,setCity]=useState('all');
  const [visibleCount,setVisibleCount]=useState(6);
  useEffect(()=>setVisibleCount(6),[tab,city]);
  const leads=data.leads.filter(lead=>isOpenLead(lead)&&(city==='all'||lead.city===city));
  const due=leads.filter(lead=>['overdue','today'].includes(followUpState(lead))).sort((a,b)=>a.nextFollowUp.localeCompare(b.nextFollowUp));
  const upcoming=leads.filter(lead=>followUpState(lead)==='upcoming').sort((a,b)=>a.nextFollowUp.localeCompare(b.nextFollowUp));
  const review=leads.filter(lead=>lead.stage==='New').sort((a,b)=>b.score-a.score);
  const drafts=data.drafts.filter(draft=>draft.status==='draft'&&leads.some(lead=>lead.id===draft.leadId));
  const current=tab==='due'?due:tab==='upcoming'?upcoming:review;
  const tabs=[{id:'due',label:'Due now',count:due.length,icon:Clock},{id:'upcoming',label:'Upcoming',count:upcoming.length,icon:CalendarDays},{id:'review',label:'Review prospects',count:review.length,icon:Target},{id:'drafts',label:'Review drafts',count:drafts.length,icon:Mail}] as const;
  const loggedToday=data.leads.flatMap(lead=>lead.contactHistory??[]).filter(log=>businessDate(new Date(log.createdAt))===businessDate()).length;
  return <>
    <PageHeading eyebrow="YOUR DAILY SALES PLAN" title="Today’s actions" description="Start with follow-ups. Record the outcome, choose the next step, then move on to a new prospect."><Button variant="secondary" icon={Search} onClick={()=>browse()}>Find businesses</Button></PageHeading>
    <div className="today-summary"><div><span className="today-calendar"><CalendarDays size={25}/></span><div><strong>{new Date().toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',weekday:'long',day:'numeric',month:'long'})}</strong><p>{due.length?`${due.length} follow-up${due.length===1?'':'s'} need attention.`:'Your scheduled follow-ups are up to date.'} Dates use India time.</p></div></div><span><CheckCircle2 size={17}/>{loggedToday} contact updates logged today</span></div>
    <div className="action-tabs" role="tablist" aria-label="Daily action lists">{tabs.map(item=><button role="tab" aria-selected={tab===item.id} key={item.id} onClick={()=>setTab(item.id)} className={tab===item.id?'active':''}><item.icon size={18}/><span>{item.label}</span><strong>{item.count}</strong></button>)}</div>
    <section className="card daily-list"><CardHeading title={tab==='due'?'Follow up with these businesses':tab==='upcoming'?'Plan your next conversations':tab==='review'?'Decide who belongs on your shortlist':'Messages waiting for your review'} subtitle={tab==='review'?'Check the source and suggested products, then qualify the business.':tab==='drafts'?'Confirm the recipient and edit the message before sending.':'After your call or meeting, record what happened and choose the next date.'}><select aria-label="Today city filter" value={city} onChange={e=>setCity(e.target.value)}><option value="all">All cities</option>{[...new Set(data.leads.map(lead=>lead.city))].map(c=><option key={c}>{c}</option>)}</select></CardHeading>
      {tab==='drafts'?(drafts.length?<div className="daily-rows">{drafts.map(draft=><div className="daily-row" key={draft.id}><Avatar name={draft.leadName}/><div className="daily-business"><strong>{draft.leadName}</strong><p>{draft.subject}</p><small>{draft.engine==='openai'?'AI draft':'Catalogue template'} · recipient needs review</small></div><Button variant="secondary" icon={Mail} onClick={()=>openDraft(draft)}>Review draft</Button></div>)}</div>:<EmptyState icon={Mail} title="No drafts waiting" text="Open a shortlisted business and prepare an introduction when you have checked its contact details." action={<Button onClick={()=>navigate('Saved leads')}>Open shortlist</Button>}/>):current.length?<div className="daily-rows">{current.slice(0,visibleCount).map(lead=><div className="daily-row" key={lead.id}><Avatar name={lead.name} segment={lead.segment}/><div className="daily-business"><button onClick={()=>openLead(lead)}><strong>{lead.name}</strong><ArrowUpRight size={15}/></button><p>{lead.segment} · {lead.city}</p><div className="daily-meta"><Badge tone={followUpState(lead)==='overdue'?'red':'sand'}>{tab==='review'?`Fit ${lead.score}/100`:followUpState(lead)==='overdue'?'Overdue':followUpState(lead)==='today'?'Today':lead.nextFollowUp}</Badge>{tab!=='review'&&<span>{lead.stage} · {lead.nextFollowUp}</span>}{tab==='review'&&<span>{lead.source}</span>}</div></div><div className="daily-actions">{tab==='review'?<Button variant="secondary" icon={Target} onClick={()=>openLead(lead)}>Review business</Button>:<><Button variant="secondary" icon={Phone} onClick={()=>logContact(lead)}>Log contact</Button><button className="text-link" onClick={()=>openLead(lead)}>View details <ArrowUpRight size={14}/></button></>}</div></div>)}</div>:<EmptyState icon={CalendarDays} title={tab==='due'?'No follow-ups due':tab==='upcoming'?'No upcoming follow-ups':'All current prospects have been reviewed'} text={tab==='due'?'Use this time to review a new prospect or prepare a draft.':tab==='upcoming'?'Open a business and use Log contact to schedule its next conversation.':'Discover more businesses or follow up with your shortlist.'} action={<Button onClick={()=>tab==='due'?setTab('review'):browse()}>{tab==='due'?'Review prospects':'Browse businesses'}</Button>}/>} {tab!=='drafts'&&current.length>6&&<div className="daily-list-footer"><span>Showing {Math.min(visibleCount,current.length)} of {current.length} businesses</span>{visibleCount<current.length&&<Button variant="secondary" onClick={()=>setVisibleCount(count=>count+6)}>Show more</Button>}</div>}</section>
    <div className="daily-tip"><Phone size={19}/><p><strong>Use your own phone or mailbox to make contact.</strong> Logging an update records what you did; it does not place a call or send a message.</p></div>
  </>;
}

export function ContactModal({lead,onClose}:{lead:Lead;onClose:()=>void}) {
  const {run}=useApp();
  const [channel,setChannel]=useState<ContactLog['channel']>('Call');
  const [outcome,setOutcome]=useState<ContactLog['outcome']>('Connected');
  const [summary,setSummary]=useState('');
  const [stage,setStage]=useState<Stage>(lead.stage);
  const [date,setDate]=useState(lead.nextFollowUp>=businessDate()?lead.nextFollowUp:dateAfter(2));
  const [schedule,setSchedule]=useState(isOpenLead(lead));
  const [busy,setBusy]=useState(false);
  const closed=lead.suppressed||['Won','Lost'].includes(stage);
  return <Modal title="Log a conversation" subtitle={lead.name} onClose={onClose}><form onSubmit={async event=>{event.preventDefault();setBusy(true);const result=await run(()=>api(`/leads/${lead.id}/contact-log`,{channel,outcome,summary,stage,nextFollowUp:schedule&&!closed?date:''}),'Contact update saved. Your action list is updated.');setBusy(false);if(result)onClose();}}><div className="modal-content form-stack"><p className="contact-log-intro">Record a call, email or meeting that has already happened. No message is sent from this form.</p><div className="form-row"><label>Contact method<select aria-label="Contact method" value={channel} onChange={event=>setChannel(event.target.value as ContactLog['channel'])}>{['Call','Email','Meeting'].map(item=><option key={item}>{item}</option>)}</select></label><label>Outcome<select aria-label="Outcome" value={outcome} onChange={event=>setOutcome(event.target.value as ContactLog['outcome'])}>{contactOutcomes.map(item=><option key={item}>{item}</option>)}</select></label></div><label>What happened?<textarea value={summary} onChange={event=>setSummary(event.target.value)} required minLength={3} maxLength={2000} rows={4} placeholder="E.g. The manager asked for a sugar sachet catalogue. Follow up after they review it."/></label><label>Sales stage after this contact<select aria-label="Sales stage after this contact" value={stage} onChange={event=>setStage(event.target.value as Stage)}>{stages.map(item=><option key={item}>{item}</option>)}</select></label>{!closed&&<label className="checkbox-label"><input type="checkbox" checked={schedule} onChange={event=>setSchedule(event.target.checked)}/>Schedule the next follow-up</label>}{schedule&&!closed&&<div className="next-contact"><label>Next contact date<input aria-label="Next contact date" type="date" required min={businessDate()} value={date} onChange={event=>setDate(event.target.value)}/></label><div className="date-presets">{[{label:'Tomorrow',days:1},{label:'In 3 days',days:3},{label:'Next week',days:7}].map(item=><button type="button" key={item.label} onClick={()=>setDate(dateAfter(item.days))}>{item.label}</button>)}</div></div>}{(!schedule||closed)&&<p className="small muted">Any previous follow-up date will be cleared. The contact history is retained.</p>}</div><div className="modal-footer"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button icon={Check} busy={busy}>Save contact update</Button></div></form></Modal>;
}

export function GettingStarted() {
  const {data,navigate,browse,openLead}=useApp();
  const [collapsed,setCollapsed]=useState(()=>localStorage.getItem('grow-guide-collapsed')==='true');
  const reviewed=data.leads.some(lead=>lead.saved||lead.stage!=='New');
  const steps=[
    {title:'Your market is ready',detail:'Browse researched businesses by city and category.',done:data.leads.length>0,action:()=>browse()},
    {title:'Choose a prospect',detail:'Check its source. Qualify and shortlist it.',done:reviewed,action:()=>data.leads.find(lead=>lead.stage==='New')?openLead(data.leads.find(lead=>lead.stage==='New')!):navigate('Saved leads')},
    {title:'Prepare an introduction',detail:'Confirm the purchasing contact and review your draft.',done:data.drafts.length>0,action:()=>navigate('Outreach studio')},
    {title:'Plan the follow-up',detail:'Log the conversation and choose a next contact date.',done:data.leads.some(lead=>!!lead.nextFollowUp||!!lead.contactHistory?.length),action:()=>navigate('Today')},
  ];
  const complete=steps.filter(step=>step.done).length;
  return <section className="getting-started" aria-label="Your sales workflow"><button className="getting-started-toggle" aria-expanded={!collapsed} onClick={()=>{setCollapsed(!collapsed);localStorage.setItem('grow-guide-collapsed',String(!collapsed));}}><span><span className="guide-icon"><Target size={20}/></span><span><strong>Start here: your first customer conversation</strong><small>{complete} of 4 milestones reached · click a step to continue</small></span></span><span>{collapsed?'Show steps':'Hide steps'}</span></button>{!collapsed&&<div className="getting-started-steps">{steps.map((step,i)=><button key={step.title} onClick={step.action}><span className={step.done?'complete':''}>{step.done?<Check size={16}/>:i+1}</span><div><strong>{step.title}</strong><p>{step.detail}</p></div><ArrowUpRight size={15}/></button>)}</div>}</section>;
}

export function SetupStatus() {
  const {data}=useApp();
  const [status,setStatus]=useState<Readiness|null>(null);
  const [error,setError]=useState('');
  useEffect(()=>{let active=true;api<Readiness>('/readiness').then(result=>{if(active)setStatus(result);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[data]);
  return <section className="card setup-status"><CardHeading title="What works right now" subtitle="Configuration status, with the next step for each capability."/>{error&&<p className="inline-warning">{error}</p>}{status?<><div className="deployment-status"><Badge tone={status.environment==='production'?'green':'sand'}>{status.environment==='production'?'Production server':'Local development'}</Badge><span>{status.environment==='production'&&status.publicUrl?'Configured address: '+status.publicUrl:'This workspace has not been published from this server.'}</span></div><div className="readiness-grid">{status.checks.map(check=><div key={check.id}><span className={check.ready?'ready':'pending'}>{check.ready?<CheckCircle2 size={20}/>:<Circle size={20}/>}</span><div><strong>{check.title}</strong><p>{check.detail}</p></div></div>)}</div><p className="readiness-note">API keys stay on your server. Configured keys are not proof of valid credentials or provider availability.</p></>:!error&&<p className="readiness-note">Checking your workspace…</p>}</section>;
}
